--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEOUL_NATURE
--------------------------------------------------------

  CREATE TABLE "HR"."SEOUL_NATURE" 
   (	"NO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"POSTER" VARCHAR2(500 BYTE), 
	"MSG" VARCHAR2(4000 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"HIT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SEOUL_NATURE
SET DEFINE OFF;
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (43,'춘당지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=39708&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','창경궁 내에 있는 아름다운 춘당지','03072 서울 종로구 창경궁로 185 (와룡동, 창경궁)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (44,'효창공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=39707&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국가지정 문화재인 효창공원','04311 서울 용산구 효창원로 177-18 (효창공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (45,'서리풀 공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=39706&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','각 계절의 아름다움을 느낄 수 있는 도심 속 서리풀공원','137-070 서울특별시 서초구 서초동 1005-6 서리풀공원',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (46,'인왕산 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=39306&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','아름다운 야경으로 많은 사람들에게 사랑을 받는 곳','03023 서울 종로구 통일로18나길 3',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (47,'월드컵공원 반려견놀이터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38861&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','사랑스러운 반려견과 함께 목줄 없이 신나게 뛰어놀 수 있는 공간','03901 서울 마포구 증산로 32 (상암동, 안내소)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (48,'응봉산 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38786&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','반짝이는 서울 도심 야경을 즐길 수 있는 곳','04743 서울 성동구 독서당로 362 (응봉산팔각정 공중화장실)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (50,'수성동계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37952&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','수성동계곡은 겸재 정선의 ''장동팔경첩'' 수성동 그림으로 등장할 정도로 아름다운 계곡으로 알려져 내려왔다. 안평대군과 겸재 정선이 자주 찾아와 아름다운 수성동계곡을 바라보며 한문과 예술을 즐겼다고 한다.','03034 서울 종로구 옥인동 185-3 수성동 계곡',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (51,'지양산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37532&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','지양산은 856m 길이의 무장애 숲길로 유명하며 데크로 이루어진 넓은 오솔길이다.','08037 서울 양천구 신월동 산 158-1',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (52,'백련산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37529&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서대문구에 위치한 백련산은 북한산과 인왕산 등 주변 산들에 비해 완만한 경사를 가지고 있다.','03651 서울 서대문구 홍은동',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (53,'안산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37364&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울 서대문에 있는 295.5 미터 산','서울 서대문구 봉원동 산 2-1',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (54,'경의선 숲길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37160&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','도심속의 녹지, 주민들의 산책로','서울시 마포구 연남동',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (55,'일자산허브천문공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37130&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','24시간 이용 가능한 천문대가 있는 허브 공원','134-060 서울 강동구 둔촌동 산86',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (56,'광진숲나루','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37010&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','천호대로 터널 상부에 위치한 근린공원','04982 서울 광진구 광장로 11',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (57,'서초문화예술공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36989&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','플라타너스 숲이 예쁜 양재시민의 숲 제 3구역 공원','06769 서울 서초구 바우뫼로12길 40 (양재동, 서초문화예술공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (58,'서순라길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36973&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종묘를 순찰하는 순라청 근처 길','03139 서울 종로구 종로 지하 129 (1호선 종로3가역)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (59,'살곶이길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36971&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','가을에 은행나무와 억새를 구경하기 좋은 길','04792 서울 성동구 광나루로 200',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (60,'화랑로 낙엽거리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=8020&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','태릉 입구에서 삼육대로 이어지는 가을 단풍과 낙엽이 아름답기로 유명한 거리','01805 서울특별시 노원구 공릉동 육군사관학교 일대',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (61,'매봉산 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16326&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','한강위로 은은히 비치는 대교와 가로등의 불빛, 화려한 강남 빌딩 숲을 볼 수 있는 곳','서울특별시 중구 신당동 매봉산 공원',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (63,'금선사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36843&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북한산자락에 위치한 아름다운 절','03000 서울 종로구 비봉길 137 (구기동, 금선사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (26,'홍릉시험림(홍릉숲)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2029&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국립산림과학원 홍릉시험림은 근대 임업시험 연구의 최초 시험지라는 역사적, 문화적, 학술적 가치가 높은 곳이다. 여러 가지 임업시험 및 연구과제를 수행하는 산림과학 연구 시험림이며 국내외 다양한 식물유전자원이 있다.','02455 서울 동대문구 회기로 57 (청량리동, 국립산림과학원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (62,'가을단풍길 - 남산남측순환로','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36947&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','남산 국립극장교차로부터 남산 3호 터널까지 총 1.3km에 이르는 길','04340 서울 용산구 남산공원길 126 (용산동2가)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (64,'화랑대 철도공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35622&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','옛 화랑대역을 공원화한 경춘선숲길 마지막 구간','01802 서울 노원구 화랑로 608 (공릉동) 화랑대 철도공원',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (65,'금선사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36843&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북한산자락에 위치한 아름다운 절','03000 서울 종로구 비봉길 137 (구기동, 금선사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (66,'화랑대 철도공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35622&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','옛 화랑대역을 공원화한 경춘선숲길 마지막 구간','01802 서울 노원구 화랑로 608 (공릉동) 화랑대 철도공원',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (67,'마포구 메타세쿼이아 숲길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35621&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','사계절 내내 즐길 수 있는 나무가 울창한 숲길','03900 서울 마포구 하늘공원로 95 (상암동, 탐방객안내소) 메타세쿼이아 숲길',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (68,'중랑캠핑숲','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35307&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','학생소풍 및 가족단위 피크닉을 주제로 한 체험형 공원','02062 서울 중랑구 망우로87길 110 (망우동, 캠핑장관리소) 중랑캠핑장',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (70,'난지천공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35072&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','물과 들이 만난 자연과 가까운 걷기 좋은 공원','03900 서울 마포구 월드컵로 365 (난지천공원 잔디광장매점) 난지천공원 주차장',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (71,'개화산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32823&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','강서구 방화동에 위치한 산이며 행주산성과 한강을 사이에 두고 마주보고 있다. 둘레길이 잘 조성되어 있어 산책하기에도 안성맞춤 명소이다.','07601 서울 강서구 양천로 22 (방화동, 개화산역) 개화산',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (73,'개화산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32823&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','강서구 방화동에 위치한 산이며 행주산성과 한강을 사이에 두고 마주보고 있다. 둘레길이 잘 조성되어 있어 산책하기에도 안성맞춤 명소이다.','07601 서울 강서구 양천로 22 (방화동, 개화산역) 개화산',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (93,'녹사평역 지하예술정원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29239&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','녹사평역 지하예술정원은 서울은 미술관 프로젝트의 일환인 녹사평역 공공미술 프로젝트를 통해 새롭게 재탄생한 도심 속 정원이다.','04353 서울 용산구 녹사평대로 지하 195 (용산동4가, 6호선 녹사평역)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (94,'어린이대공원 반려견 놀이터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28776&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','어린이대공원 반려견 놀이터는 반려견들이 목줄 없이 자유롭게 뛰어놀 수 있는 환경을 만들기 위해 만들어졌다.','04991 서울 광진구 능동로 216 (능동, 어린이대공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (96,'솔밭근린공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29458&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','솔밭근린공원은 강북구 우이동에 위치한 소나무 숲공원이다.','01007 서울 강북구 삼양로 561 (우이동, 솔밭공원 관리실및화장실)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (97,'녹사평역 지하예술정원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29239&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','녹사평역 지하예술정원은 서울은 미술관 프로젝트의 일환인 녹사평역 공공미술 프로젝트를 통해 새롭게 재탄생한 도심 속 정원이다.','04353 서울 용산구 녹사평대로 지하 195 (용산동4가, 6호선 녹사평역)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (98,'어린이대공원 반려견 놀이터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28776&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','어린이대공원 반려견 놀이터는 반려견들이 목줄 없이 자유롭게 뛰어놀 수 있는 환경을 만들기 위해 만들어졌다.','04991 서울 광진구 능동로 216 (능동, 어린이대공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (100,'백범광장공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28656&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','백범광장공원은 서울 중구 회현동 남산공원을 올라가는 도중 산 중턱에 위치한다.','04633 서울 중구 퇴계로8길 49-4',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (101,'사직공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28280&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','사직공원은 종로구 사직동에 위치한 공원이다.','03027 서울 종로구 사직로9길 5 (사직동, 사직근린공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (102,'노을공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27691&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','90년대까지 난지도란 이름의 쓰레기 매립장이었던 노을공원은 환경 재생사업을 통해 월드컵공원으로 탈바꿈하면서 이제는 사계절 내내 멋진 노을을 감상할 수 있는 명소가 되었다.','03900 서울 마포구 하늘공원로 84 (상암동, 한국지역난방공사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (103,'어린이대공원 반려견 놀이터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28776&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','어린이대공원 반려견 놀이터는 반려견들이 목줄 없이 자유롭게 뛰어놀 수 있는 환경을 만들기 위해 만들어졌다.','04991 서울 광진구 능동로 216 (능동, 어린이대공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (105,'백범광장공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28656&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','백범광장공원은 서울 중구 회현동 남산공원을 올라가는 도중 산 중턱에 위치한다.','04633 서울 중구 퇴계로8길 49-4',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (106,'사직공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28280&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','사직공원은 종로구 사직동에 위치한 공원이다.','03027 서울 종로구 사직로9길 5 (사직동, 사직근린공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (8,'여의도 한강공원(소녀시대숲)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=12993&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','여의도 한강공원에는 다양한 k-pop 아이돌 그룹들의 이름을 따 팬들이 기부한 돈으로 조성된 숲들이 있다.','07231 서울특별시 영등포구 여의도 여의서로(윤중로)',2);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (9,'어린이대공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1853&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','어린이대공원은 서울 광진구에 위치해 있으며 가족 단위의 휴식공간이다. 동물나라, 놀이동산, 자연나라 등으로 구성되어있다.','04991 서울특별시 광진구 능동로 216, 서울어린이대공원(능동)',9);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (10,'서울숲','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1840&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','서울의 숲을 잇는 ´자연의 거점´서울숲','04770 서울특별시 성동구 뚝섬로 273 (성수동1가)',5);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (11,'하늘공원 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16322&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','월드컵공원의 5개의 공원 중 하늘과 가장 가까이 맞닿아 있다 해서 이름 붙여진 하늘공원은 난지캠핑장 옆에 위치한 생태환경공원이다.','03900 서울 마포구 하늘공원로 95 (상암동, 탐방객안내소)',5);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (12,'하늘공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3833&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','하늘공원은 2002년 제17회 월드컵축구대회를 기념하며 난지도 쓰레기매립장을 복원하기 위해 개원한 월드컵경기장 일대 5대 공원 중 하나이다.','03900 서울 마포구 하늘공원로 95 (탐방객안내소)',3);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (13,'서울대공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5479&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','경기도 과천시 청계산 아래에 있는 서울대공원은 1984년에 개원한 한국 최초의 동물원이다.','13829 경기 과천시 대공원광장로 102 (막계동, 서울대공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (14,'낙산공원 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16320&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','한양도성의 성벽선과 어우러지는 도심의 현재 모습을 조망할 수 있는 곳','03085 서울특별시 종로구 낙산길 41',1);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (15,'낙산공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3701&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울의 좌청룡 낙산종로와 성북구에 걸쳐 자리한 낙산(駱山)은 서울시민과 이제 막 정이 들어가고 있다. 지난 2000년 11월에야 다시금 서울 시민들을 마주했으니 다시 만난 지 채 10년도 지나지 않았다.','03085 서울 종로구 낙산길 41 (동숭동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (16,'홍익문화공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11072&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','홍대입구역에서 가까운 홍대 놀이터에서는 예술시장인 프리마켓이 자주 열린다.','04040 서울 마포구 와우산로21길 19-3 서교빌딩',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (17,'백악(북악)산 (서울 한양도성)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3798&fileTy=POSTTHUMB&fileNo=5&thumbTy=M','백악(북악)산 한양도성은 청와대와 인접해 있다.자연 속 서울 성곽 산행 코스로도 유명해 많은 방문객이 찾고 있다.','03038 서울 종로구 옥인6길 26-17',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (18,'석촌호수 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16328&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','석촌호수는 서울 송파구 잠실동에 있는 호수이다.','05608 서울 송파구 삼학사로 136 (잠실동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (19,'석촌호수공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1136&fileTy=POSTTHUMB&fileNo=5&thumbTy=M','서울 시민들에게 사랑받는 휴식처','05608 서울 송파구 삼학사로 136 (서울놀이마당)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (20,'인왕산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3840&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','태소, 무학대사의 기도터, 서울 외각을 쌓았던 서울 도성이 남아있는 인왕산','110-080 서울특별시 종로구 통일로18가길 20 (무악동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (21,'선유도 공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=379&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','우리나라 최초의 재활용 생태 공원서울시 공원은 닮은 듯 다른 저마다의 색깔을 가진다.','07200 서울 영등포구 선유로 343 (당산동, 선유도공원)',2);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (22,'관악산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4399&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','관악산은 1968년 도시자연공원으로 지정되었다.','151-019 서울특별시 관악구 대학동 일대',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (75,'남산서울타워 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16321&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','남산서울타워에서 내려다보이는 야경은 서울을 대표하는 10대 한류 명소로 손꼽힌다.','04340 서울 용산구 남산공원길 105 (용산동2가, YTN서울타워)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (76,'노들섬','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=31922&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','용산구에 위치한 노들섬은 자연, 음악, 책과 쉼이 있는 시간을 보낼 수 있는 복합문화시설이다.','04427 서울 용산구 양녕로 445 (이촌동) 노들섬',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (77,'서소문역사공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29945&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서소문역사공원은 원래 서소문근린공원을 대폭 리모델링하여 지상1층~지하4층 연면적 4만 6천여㎡ 규모로 2019년 조성된 공원이다.','04510 서울 중구 칠패로 5 (서소문공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (78,'삼천사계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29802&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','삼천사계곡은 북한산 국립공원 내에 위치한 삼천사 인근에 흐르는 계곡이다.','03308 서울 은평구 연서로54길 127 (진관동, 삼천사) 인근',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (79,'진관사계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29800&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','급한 경사를 따라 이어진 암반과 풍경이 절경을 이루는 계곡','03308 서울 은평구 진관길 73 (진관동, 진관사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (80,'우이동계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29798&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','맑고 시원한 계곡물이 흐르는 우이동계곡은 도봉산과 북한산 사이에 있다.','01000 서울 강북구 삼양로181길 141-5 (우이산장)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (81,'노들섬','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=31922&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','용산구에 위치한 노들섬은 자연, 음악, 책과 쉼이 있는 시간을 보낼 수 있는 복합문화시설이다.','04427 서울 용산구 양녕로 445 (이촌동) 노들섬',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (82,'서소문역사공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29945&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서소문역사공원은 원래 서소문근린공원을 대폭 리모델링하여 지상1층~지하4층 연면적 4만 6천여㎡ 규모로 2019년 조성된 공원이다.','04510 서울 중구 칠패로 5 (서소문공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (83,'삼천사계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29802&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','삼천사계곡은 북한산 국립공원 내에 위치한 삼천사 인근에 흐르는 계곡이다.','03308 서울 은평구 연서로54길 127 (진관동, 삼천사) 인근',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (84,'진관사계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29800&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','급한 경사를 따라 이어진 암반과 풍경이 절경을 이루는 계곡','03308 서울 은평구 진관길 73 (진관동, 진관사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (85,'우이동계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29798&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','맑고 시원한 계곡물이 흐르는 우이동계곡은 도봉산과 북한산 사이에 있다.','01000 서울 강북구 삼양로181길 141-5 (우이산장)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (86,'백사실계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29797&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북악산에 위치한 백사실계곡은 서울에서 보기 드물게 흐르는 물이 깨끗하고 주변 숲 또한 잘 보존되어 있는 곳이다.','03019 서울 종로구 세검정로6길 98',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (87,'푸른수목원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29796&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','구로구에 위치한 푸른수목원은 서울시 최초로 조성되는 시립수목원으로 교육프로그램과 친환경관리의 중심인 "생태의 섬"이다.','08361 서울 구로구 연동로 240 (항동, 푸른수목원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (88,'배봉산근린공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29459&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','해발 106m의 배봉산에 조성된 배봉산근린공원은 산지형 공원으로 비탈졌으나 무장애 둘레길이 있어 수월하게 오를 수 있는 공원이다.','02509 서울 동대문구 한천로43길 12-14 (전농동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (89,'백사실계곡','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29797&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북악산에 위치한 백사실계곡은 서울에서 보기 드물게 흐르는 물이 깨끗하고 주변 숲 또한 잘 보존되어 있는 곳이다.','03019 서울 종로구 세검정로6길 98',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (90,'푸른수목원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29796&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','구로구에 위치한 푸른수목원은 서울시 최초로 조성되는 시립수목원으로 교육프로그램과 친환경관리의 중심인 "생태의 섬"이다.','08361 서울 구로구 연동로 240 (항동, 푸른수목원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (91,'배봉산근린공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29459&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','해발 106m의 배봉산에 조성된 배봉산근린공원은 산지형 공원으로 비탈졌으나 무장애 둘레길이 있어 수월하게 오를 수 있는 공원이다.','02509 서울 동대문구 한천로43길 12-14 (전농동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (92,'솔밭근린공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29458&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','솔밭근린공원은 강북구 우이동에 위치한 소나무 숲공원이다.','01007 서울 강북구 삼양로 561 (우이동, 솔밭공원 관리실및화장실)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (107,'노을공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27691&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','90년대까지 난지도란 이름의 쓰레기 매립장이었던 노을공원은 환경 재생사업을 통해 월드컵공원으로 탈바꿈하면서 이제는 사계절 내내 멋진 노을을 감상할 수 있는 명소가 되었다.','03900 서울 마포구 하늘공원로 84 (상암동, 한국지역난방공사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (108,'봉산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27690&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울 은평구와 경기도 고양 사이에 있는 봉산은 서울 서쪽의 경계를 이룬 산이다.','03424 서울 은평구 서오릉로23길 8-5 (수국사)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (109,'아차산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27689&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','한강과 도시가 어우러진 풍경을 즐길 수 있는 아차산','04948 서울 광진구 영화사로 135 (아차산등산로 입구)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (110,'서래섬','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27688&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서래섬은 동작대교와 반포대교 사이에 있는 작은 인공 섬이다.','06500 서울 서초구 신반포로11길 40 (반포동, 한강공원 반포 안내센터)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (1,'도봉산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3599&fileTy=POSTTHUMB&fileNo=5&thumbTy=M','하늘을 깎아세운 만길 봉우리도봉(道峰)산은 이름 그대로 봉우리가 길인 산','132-010 서울특별시 도봉구 도봉동 경기 의정부시, 양주시 장흥면 일대',37);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (2,'청계천','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34&fileTy=POSTTHUMB&fileNo=6&thumbTy=M','600년 서울의 역사가 하천의 물길 속으로 종로구와 중구 사이를 가르는 10.84km의 하천. 600년 수도 서울이 가지는 역사이기도 하고, 서울 시민 개개인이 가진 소소한 추억이기도 하다.','03187 서울 종로구 무교로 37 (서린동)',24);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (3,'남산공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3633&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','남산공원은 서울에 있는 공원 중에서 가장 넓은 시민공원이다. 크게 장충지구와 예장지구, 회현지구, 한남지구로 나눌 수 있다.','04628 서울특별시 중구 삼일대로 231',19);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (4,'한강','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=15060&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','한강은 서울에서 가장 중요한 지표로 도시를 남과 북으로 나눈다. 강변 양쪽으로 공원이나 다른 휴양시설이 다양해 자전거를 즐기거나, 크루즈를 타거나, 조류 관찰을 하기에도 알맞다.','07243 서울 영등포구 여의공원로 68',5);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (5,'북한산국립공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=369&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','1년 내내 새 코스를 발견하는 재미북한산국립공원은 산성 주능선, 우이능선, 비봉능선, 형제능선, 의상능선, 진달래능선 등 수많은 능선과 계곡이 펼쳐져 있어 1년 내내 오르내려도 늘 새롭다.','02700 서울 성북구 보국문로34길 6-21 (정릉동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (6,'여의도 공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2161&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','여의도 공원은 서울 영등포구 여의도동에 위치한 시민공원이다.','07243 서울 영등포구 여의공원로 68 (여의도동, 여의도공원관리사무소)',2);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (7,'올림픽공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2139&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울올림픽을 기념하며 올림픽공원은 서울올림픽을 기념해 조성한 공원이다. 1984년에 2년 후의 아시안게임과 4년 후의 올림픽을 앞두고 공사를 시작했다.','05540 서울 송파구 올림픽로 424 (방이동, 올림픽공원)',2);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (23,'북서울꿈의숲','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4823&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','북서울꿈의숲은 복잡한 도심 속에서 시원하게 트인 풍경과 자연을 만날 수 있는 대형 녹지 공원이다.','01228 서울특별시 강북구 월계로 173 (번동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (24,'보라매공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2189&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','동작구 신대방동에 있는 보라매공원은 과거 공군사관학교로 사용되던 중 서울시에서 인수해 복지 및 편의시설이 마련된 시립공원으로 재탄생했다.','07062 서울 동작구 여의대방로20길 33 (신대방동, 보라매공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (25,'양재시민의 숲','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2158&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','양재시민의 숲은 서울 서초구 양재동에 위치한 공원','06773 서울특별시 서초구 매헌로 99 (양재동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (27,'여의도샛강생태공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5032&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','여의도 샛강 생태공원은 생태계 보전을 위해 마련된 국내 최초의 생태공원이다.','07323 서울 영등포구 여의동로 48 (여의도샛강생태공원 방문자센터)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (28,'토성산성어울길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6606&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','토성산성어울길은 몽촌토성에서 남한산성까지 이어진다 하여 명칭을 얻었으며 크게 몽촌토성길과 남한산성 두 개의 코스로 나뉜다.','서울특별시 송파구 올림픽로 424 (방이동) 올림픽공원',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (29,'몽촌토성','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2210&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','올림픽공원 내 자리해 있는 몽촌토성은 백제 초기의 토성으로 전체 둘레는 약 2.7㎞에 달한다.','05540 서울특별시 송파구 올림픽로 424 (방이동)',1);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (30,'낙성대 공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3008&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','강감찬 장군을 기려 조성한 낙성대 공원은 서울특별시 관악구 봉천동에 위치해 있다.','08799 서울 관악구 낙성대로 77 (봉천동, 낙성대공원)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (31,'망원 한강공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2841&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','성산대교와 양화대교 사이 한강 북단에 만들어진 망원지구는 아름다운 전망과 역사유적이 많은 곳이다.','04005 서울특별시 마포구 마포나루길 467 (망원동) 한강공원망원지구사무소',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (32,'월드컵공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2119&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','1978~93년 15년간 쌓인 쓰레기 매립지는 거대한 산을 이뤘다. 하지만 서울시의 ''골칫덩어리'' 매립지 위에 생태공원이 조성되면서 지금은 서울시민의 가장 사랑받는 월드컵 공원으로 거듭났다','03900 서울특별시 마포구 하늘공원로 108-1',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (33,'청운공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3136&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울특별시 종로구 청운동에 위치한 청운공원은 자하문 옆 윤동주 시인의 언덕부터 청운 어린이집 부근까지 포괄해서 일컫는다.','서울시 종로구 창의문로 119 (청운동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (34,'불암산','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3828&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','노원구와 남양주시에 걸쳐있는 불암산은 산 정상에 있는 큰 바위가 송낙을 쓴 부처님의 모습을 닮았다고 하여 불암산이라는 명칭을 갖게 되었다.','01716 서울특별시 노원구 덕릉로94길 73 (중계동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (35,'길동생태공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4064&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','길동자연생태공원은 시민들에게 동·식물, 곤충들이 자연 속에서 활동하는 모습을 관찰할 수 있도록 하기 위해 조성되었다.','05291 서울 강동구 천호대로 1291 (길동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (36,'북악산 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16324&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','북악산은 보안상의 이유로 서울의 많은 산 중에서 가장 늦게 개방되었다.','03010 서울 종로구 북악산로 267 (평창동, 북악팔각정)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (37,'서서울호수공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4928&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','신월정수장이 문을 닫으며 재탄생된 생태공원','07916 서울 양천구 남부순환로64길 20 (신월동, 공원관리사무소)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (38,'도산공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1789&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','도산공원은 서울 강남구 신사동에 있는 공원으로 도산 안창호의 애국정신과 교육 정신을 기리고자 조성되었다.','06020 서울 강남구 도산대로45길 20 (도산전시관)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (39,'마포대교 바람의 길 & 서울색공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11237&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','여의도 랜드마크 중 하나인 바람의 길은 한강과 서울의 경치를 감상할 수 있는 전망대 기능의 대형조형물이다.','07337 서울 영등포구 여의동로 330 (여의도동, 한강사업본부 여의도안내센터)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (40,'마로니에공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2087&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','마로니에공원은 젊음과 문화의 상징인 대학로라는 공간의 특성과 상통하는 문화적 향취를 가진 곳이다.','03086 서울 종로구 대학로8길 1 (동숭동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (41,'현대원서공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=12315&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','현대원서공원은 현대건설이 그룹 사옥건립 때 기업 이익의 사회 환원과 시민 휴식을 위한 녹지 공간 조성을 목적으로 만든 곳이다.','03058 서울특별시 종로구 창덕궁길 19 (원서동)',0);
Insert into HR.SEOUL_NATURE (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (42,'뚝섬유원지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11399&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','뚝섬유원지는 뚝섬의 한강 변 일대에 조성된 시민공원이다. 야외수영장, 놀이터, 스케이트보드장, 클라이밍장 등 각종 편의시설이 구비되어 있어 여름에는 수상스포츠를, 겨울에는 눈썰매와 스케이트를 즐길 수 있다.','05097 서울특별시 광진구 강변북로 139 (자양동)',0);
--------------------------------------------------------
--  DDL for Index SN_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SN_NO_PK" ON "HR"."SEOUL_NATURE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEOUL_NATURE
--------------------------------------------------------

  ALTER TABLE "HR"."SEOUL_NATURE" MODIFY ("TITLE" CONSTRAINT "SN_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_NATURE" MODIFY ("POSTER" CONSTRAINT "SN_POSTER_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_NATURE" MODIFY ("MSG" CONSTRAINT "SN_MSG_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_NATURE" MODIFY ("ADDRESS" CONSTRAINT "SN_ADRESS_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_NATURE" ADD CONSTRAINT "SN_NO_PK" PRIMARY KEY ("NO")
  USING INDEX "HR"."SN_NO_PK"  ENABLE;
