--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEOUL_LOCATION
--------------------------------------------------------

  CREATE TABLE "HR"."SEOUL_LOCATION" 
   (	"NO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"POSTER" VARCHAR2(500 BYTE), 
	"MSG" VARCHAR2(4000 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"HIT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SEOUL_LOCATION
SET DEFINE OFF;
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (75,'한국은행화폐박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2730&fileTy=POSTTHUMB&fileNo=5&thumbTy=M','한국은행본관에서는 국내·외 화폐 20,000여 점의 전시를 비롯해 화폐의 제조과정부터 한국 경제의 발전과정까지 방대한 자료를 제공하고 있다.','100-794 서울특별시 중구 남대문로 39, 한국은행건물 (남대문로3가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (76,'세빛섬','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24645&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','세빛섬은 서울 도심 한가운데의 한강 수변에서 문화와 여가를 즐길 수 있는 문화 복합공간이자 랜드마크다.','06500 서울 서초구 올림픽대로 2085-14 (반포동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (77,'보신각(상설타종행사)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1904&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','보신각은 서울 종로구 종로 2가에 있는 종각으로 서울보신각종을 걸어 놓기 위해 만든 것이다.','03189 서울 종로구 종로 54 (관철동, 보신각)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (78,'국회의사당','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5765&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','여의도에 위치한 국회의사당은 한국의 민주주의와 인권을 상징하는 건물이다. 국회의사당 본관이 있고 그 오른쪽에는 국회도서관이, 왼쪽에는 의원회관이 있다.','07233 서울특별시 영등포구 의사당대로 1 (여의도동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (79,'국립현대미술관 덕수궁관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1708&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','국립현대미술관 덕수궁관은 1998년 덕수궁 내 분관으로 개관하였다.','04519 서울특별시 중구 세종대로 99 (정동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (80,'도산공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1789&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','도산공원은 서울 강남구 신사동에 있는 공원으로 도산 안창호의 애국정신과 교육 정신을 기리고자 조성되었다.','06020 서울 강남구 도산대로45길 20 (도산전시관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (81,'정릉','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3461&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','정릉은 태조의 계비 신덕왕후의 능으로, 극진히 사랑했던 신덕왕후가 갑자기 승하하자 태조는 도성 안 덕수궁 뒤편에 능역을 조성했다.','02813 서울 성북구 아리랑로19길 116 (정릉동, 정릉)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (82,'안중근의사기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4281&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','안중근의사 기념관은 1909년 이토 히로부미를 사살한 독립운동가 안중근 의사를 추모하는 기념관이다.','04636 서울 중구 소월로 91 (남대문로5가, 안중근의사기념관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (83,'아름다운 차박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4471&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','종로구 인사동에 위치한 아름다운 차 박물관에서는 차와 관련된 유물을 수집, 관리 및 전시하고 있다.','03162 서울 종로구 인사동길 19-11',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (84,'국립어린이민속박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5134&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','국립어린이민속박물관에서는 어린이를 대상으로 한국의 전통문화를 직접 배울 수 있는 체험프로그램을 제공한다.','03045 서울 종로구 삼청로 37 (세종로, 국립민속박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (85,'환구단(원구단)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4198&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','환구단은 하늘에 천자가 제사를 드리는 제천단이다.','서울시 중구 소공로 106 (소공동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (86,'한성백제박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11610&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','한성백제박물관은 송파구의 고대역사 유적지에 설립된 시립박물관으로 백제의 역사와 유적을 보존하고 있는 곳이다.','05540 서울 송파구 위례성대로 71 (방이동, 한성백제박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (87,'서울올림픽기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5334&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울올림픽기념관은 88서울올림픽을 기념하고 올림픽 정신을 계승 및 발전하고자 설립되었다.','05540 서울 송파구 올림픽로 424 (방이동, 올림픽공원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (88,'북악스카이웨이 팔각정','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11117&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울 하늘에 맞닿은 전망대연인들의 데이트 코스로 손꼽히는 북악스카이웨이는 남산서울타워와는 또 다른 각도로 서울 전체를 볼 수 있는 곳이다.','03010 서울시 종로구 북악산로 267 (평창동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (89,'약현성당','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1846&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','중구 중림동에 있는 약현성당은 우리나라 최초의 서양식 벽돌조 고딕성당이다.','04506 서울시 중구 청파로 447-1',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (90,'의학박물관 (구 대한의원)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=846&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','의학박물관(구 대한의원)은 서울대학교 의과대학에 있는 조선 말기의 건물이다.','03080 서울특별시 종로구 대학로 101 (연건동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (91,'배재학당역사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6433&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','배재학당역사박물관은 한국 최초의 서양식 학교건물이자 근대식 중등 교육기관이다. 옛 배재학당의 교실로 사용된 바 있으며 현재는 상설전시관, 기획전시관, 체험교실, 세마나실로 조성되어 있다.','04516 서울특별시 중구 서소문로11길 19, 배재정동빌딩 동관 (정동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (92,'창의문','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3266&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','서울 성곽의 4소문 중 하나로 북문 또는 자하문으로도 불리는 창의문은 서울 종로구 청운동에 자리해있는 조선시대 성문이다.','03020 서울특별시 종로구 창의문로 118 (부암동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (93,'쇳대박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1427&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','2003년 대학로에 적갈색의 건축물 하나가 들어섰다. 승효상의 쇳대박물관이다. 승효상은 코르텐 강(내후성 강판, 녹슨 철의 느낌) 소재로 자신의 미학을 드러냈다.','110-810 서울특별시 종로구 이화장길 100 (동숭동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (1,'양화진외국인선교사묘원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1153&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','양화진외국인선교사묘원은 서울 마포구 합정동에 위치한 외국인 선교사들의 공동묘지이다.','04084 서울 마포구 양화진길 46 (합정동, 양화진홍보관)',180);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (2,'호림박물관 (신사분관)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5548&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','호림박물관 신사분관은 총 세 개의 건물로 이루어져 있으며, 그중 5층 규모의 박물관동 2, 3, 4층에서 고미술품을 비롯한 현대 작가들의 기획전을 전시하고 있다.','06021 서울 강남구 도산대로 317 (신사동, 호림아트센터 1빌딩)',43);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (3,'갤러리 학고재','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1872&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','갤러리 학고재는 ‘옛것을 배워 새것을 만든다’는 이념을 담고 있다. 갤러리 학고재의 본관 건물은 전통 한옥으로, 신관 건물은 21세기 건축 양식으로 만들어져 개성 있게 조화를 이루고 있다.','03053 서울특별시 종로구 삼청로 50 (소격동)',27);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (4,'송은(SONGEUN)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3778&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','송은은 송은미술대상, 국내외 작가 개인전, 특정 국가 기획전 및 컬렉션전 등의 기획전시와 더불어 국내외 동시대 미술을 조명하고 미술과 대중을 연결하고자 다양한 프로그램을 선보이는 비영리 문화공간이다.','06016 서울 강남구 도산대로 441 (청담동)',4);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (5,'김종영 미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2066&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','김종영 미술관은 한국현대조각의 선구자로 불리는 조각가 김종영을 기리며 동시에 젊은 작가들을 후원하기 위해 설립되었다.','03004 서울특별시 종로구 평창32길 30 (평창동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (6,'경희대학교 한의학역사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6889&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','경희대학교 한의학 역사박물관에는 고전 의서, 임상기록, 한의학에 관련한 유물 등이 전시되어 있다.','02453 서울 동대문구 경희대로 26-6 (회기동, 경희대학교)',28);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (7,'경복궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=72&fileTy=POSTTHUMB&fileNo=6&thumbTy=M','조선 왕조 개국 3년인 1395년에 완공된 경복궁은 이때부터 한양의 중심이 되었다. 조선왕조의 정궁으로 큰 규모와 보다 엄격한 격식이 특징적이다.','03045 서울 종로구 사직로 161 (세종로, 경복궁)',3);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (8,'창덕궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=295&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','세계가 보존하는 세계문화유산창덕궁은 서울에서 두 번째로 유네스코 선정 세계문화유산으로 등재되었다. 가장 먼저 종묘가 선정됐고 이어 창덕궁이 등재됐다.','03072 서울 종로구 율곡로 99 (와룡동, 창덕궁)',4);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (9,'전쟁기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=859&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','전쟁기념관에 들어서면 ''형제의 상''이 가장 먼저 눈에 들어온다. 현대사의 슬픔을 고스란히 보여준다.','04353 서울 용산구 이태원로 29 (용산동1가, 전쟁기념관)',27);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (10,'국립중앙박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=433&fileTy=POSTTHUMB&fileNo=11&thumbTy=M','한국 역사와 문화의 정수가 살아 숨 쉬는 국립중앙박물관은 연간 350만명의 관람객을 맞이하는 한국 최대 규모의 국립 박물관입니다. 세계 많은 나라의 문화를 소개하는 세계문화관과 최첨단 디지털 기술로 구현된 실감영상관 및 VR체험관에서 더욱 즐거운 국립중앙박물관을 만나보세요!','04383 서울 용산구 서빙고로 137 (국립중앙박물관)',19);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (11,'봉은사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=411&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','삼성역 맞은편엔 비교적 큰 규모의 사찰이 있다. 바로 봉은사다. 서울의 대표적인 사찰로 그 역사만도 1000년이 넘는다.','06087 서울 강남구 봉은사로 531 (봉은사)',20);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (12,'명동성당','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4037&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','명동성당은 우리나라 최초의 본당이며 한국 천주교회의 상징이다. 고종 29년(1892)에 착공, 광무 2년(1898)에 준공되었다.','04537 서울 중구 명동길 74 (명동성당)',8);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (13,'조계사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2587&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울 종로구 견지동에 있는 사찰인 조계사는 한국 불교의 중심 사찰이다. 조계라는 명칭은 혜능대사가 머물렀던 조계산에서 가져왔다고 한다.','03144 서울특별시 종로구 우정국로 55 (조계사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (27,'아라리오뮤지엄 인 스페이스','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=20731&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','아라리오뮤지엄은 ㈜아라리오의 창업자인 김창일 회장이 설립한 아트뮤지엄이다. 서울에 설립된 아라리오 뮤지엄은, 김수근 건축가의 대표작인 동시에 그의 사무실과 자택으로도 사용되는 등 건축사적으로 의미가 깊다.','03058 서울 종로구 율곡로 83 (원서동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (28,'롯데월드 민속박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5815&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','잠실 롯데월드 내 자리한 롯데월드 민속박물관은 시대별로 유물이 전시된 역사전시관, 조선시대 궁중의 의례장면을 축소 후 재현해 놓은 모형 촌, 전통공예품 제작과정을 볼 수 있는 저잣거리, 놀이마당 등으로 구성되어 있다.','05554 서울 송파구 올림픽로 240 (잠실동, 롯데월드)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (29,'고려대학교 본관 및 구 중앙도서관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2962&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','고려대학교 본관은 서울특별시 성북구 안암동에 있는 고려대학교의 대학본부 건물로 1981년 사적 제285호로 지정되었다.','02841 서울 성북구 안암로 145 (안암동5가, 고려대학교안암캠퍼스)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (30,'국립서울현충원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1965&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','국립현충원은 나라와 민족을 위해 순국한 영령들이 안장된 국립묘지이다. 국가유공자의 유골, 유해를 안장하고, 그 충과 의를 기리기 위해 설립되었다.','06984 서울 동작구 현충로 210 (동작동, 국립현충원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (31,'길상사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3256&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','옛 가옥 같은 절집도심과 10분 거리에 있는 시골 같은 동네, 계곡 양쪽으로 빈부가 마주보고 있는 성북동 중턱에 고즈넉한 길상사가 자리 잡고 있다. 백제나 신라 때 세워진 유서 깊은 절에 비해 역사는 짧지만 개원하면서부터 지금까지 수많은 사람들의 발길이 끊이지 않으며,','136-022 서울특별시 성북구 선잠로5길 68 (성북동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (32,'서대문자연사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2615&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서대문자연사박물관은 서대문구에 위치한 국내 최초로 공공기관이 직접 계획하고 설립한 자연사박물관이다.','03718 서울특별시 서대문구 연희로32길 51 (연희동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (33,'한국가구박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3452&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','한국가구박물관은 한국 전통 목가구 2,500여 점을 수집, 보존, 전시하는 특수 전문 박물관으로 한국의 옛 가옥 10여 채를 옮겨 놓아 실제 한옥에서 우리 가구의 쓰임새와 생활 방식을 총체적으로 볼 수 있다.','02822 서울 성북구 대사관로 121 (성북동, 한국가구박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (34,'국립중앙박물관 어린이박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=20547&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','국립중앙박물관 어린이박물관에는 다양한 옛사람들의 생활 모습을 전시하고 있다.','04383 서울 용산구 서빙고로 137 (용산동6가, 국립중앙박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (35,'명동관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11469&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','명동 관광정보센터는 서울 중구 을지로2가에 위치해 있는 관광안내소이다.','04538 서울시 중구 을지로 66 한국외환은행',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (36,'대한성공회서울주교좌성당(서울성공회성당)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2030&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','대한성공회 서울주교좌성당은 서울 중구 정동에 위치해 있다.','서울특별시 중구 세종대로21길 15 (정동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (37,'서울도서관 (옛 서울시청사)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=10231&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울도서관은 옛 서울시 시청사를 개조하여 만들어진 공공도서관이다.','04524 서울특별시 중구 세종대로 110 (태평로1가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (38,'청계천박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4696&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','청계천박물관은 지하 2층, 지상 4층 규모로 상설전시실, 기획전시실, 교육실, 소강당 등이 마련돼 있다.','04704 서울 성동구 청계천로 530 (마장동, 청계천박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (39,'화계사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2021&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','화계사는 강북구 수유동 삼각산 숲 내에 위치한 사찰로 도심과도 인접해 있어 자연의 정취를 느끼고자 많은 시민이 방문하고 있다.','01095 서울 강북구 화계사길 117 (수유동, 화계사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (40,'연세대학교 스팀슨관&언더우드관&아펜젤러관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2435&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','연세대학교 스팀슨관은 신촌동 연세대학교에 있는 근대식 건물로 1981년 사적 제275호로 지정되었다.','03722 서울특별시 서대문구 연세로 50 (신촌동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (41,'가회민화박물관　','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=18912&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','가회 민화박물관은 민화 전문 박물관으로 윤열수 관장이 개인적으로 꾸준히 수집해 온 민화와 부적관계 자료 등을 일반인들에게 공개하고 보존하기 위해 설립되었다.','03056 서울 종로구 북촌로 52 (가회동) 가회민화박물관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (42,'국립국악원박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11897&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','국립국악원박물관은 우리나라 최초의 국악 전문박물관으로 우리 고유음악의 장점을 배우고 느낄 수 있는 곳이다.','06757 서울 서초구 남부순환로 2364 (서초동, 국립국악원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (43,'국립중앙도서관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11012&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','국립중앙도서관은 한국의 지적문화유산을 체계적으로 수집해 보관하고 있는 우리나라 대표 도서관이다.','서울특별시 서초구 반포대로 201 (반포동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (44,'갤러리 현대','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1694&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','갤러리 현대는 사간동 갤러리 거리에서 가장 유명하다.','03062 서울 종로구 삼청로 14 (사간동, 현대갤러리)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (45,'금호미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3100&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','경복궁 근처에 위치한 금호미술관에서는 기성작가의 기획전을 비롯해 뛰어난 신인 작가의 기획전을 동시에 감상할 수 있다.','03062 서울 종로구 삼청로 18 (사간동, 금호미술관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (46,'헌인릉','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5242&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','헌인릉은 조선 제3대 임금인 태종과 왕비의 능인 헌릉과 제23대 순조와 왕비의 인릉을 합쳐 부르는 말이다.','06795 서울 서초구 헌인릉길 36-10 (헌인릉)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (47,'뮤지엄김치간','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=19924&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','삼성동에 위치해 있던 풀무원김치박물관이 ''뮤지엄김치간''으로 새롭게 태어났다. 뮤지엄김치간은 다양한 종류의 김치를 모형이 아닌 실물로 전시하고 있어, 직접 눈으로 관람할 수 있다.','03149 서울 종로구 인사동길 35-4 (관훈동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (48,'국제갤러리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3241&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','1982년 개관한 국제갤러리는 대표적인 국내 화랑으로서 세계적으로 유명한 현대미술 작가의 작품과 그 흐름을 접하고 감상할 수 있는 곳이다.','100-200 서울특별시 종로구 삼청로 54 (소격동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (49,'아라리오갤러리 서울','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2388&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','아시아를 대표하는 아라리오 갤러리는 서울, 천안, 중국 상하이에 운영 중이다','03053 서울특별시 종로구 북촌로5길 84 (소격동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (123,'서울생활사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38243&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울생활사박물관은 근현대 생활사 박물관으로 시민들의 기억들을 추억하고 교감할 수 있는 전시들과 프로그램이 운영되는 장소이다.','01849 서울 노원구 동일로174길 27 (공릉동) 서울생활사박물관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (124,'서울공예박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38092&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','공예의 가치를 공유하며 공예의 미래를 여는 열쇠가 되기를 지향하는 박물관','03061 서울 종로구 율곡로3길 4 (안국동, 서울공예박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (50,'한상수자수박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3358&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','중요무형문화재 제80호이자 자수장 기능보유자 한상수가 개관한 한상수 자수 박물관은 중요 방직 문화유산과 민속품을 통해 한국 전통 자수의 우수성을 알리고 있다.','02836 서울 성북구 성북로16길 4-10 (성북동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (51,'종이나라박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5797&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종이나라 박물관에서는 어린이와 학생들에게 종이의 역사와 한국 종이문화의 발전과정을 견학과 체험학습을 통해 소개하고 있다.','04606 서울 중구 장충단로 166 (장충동1가, 종이나라빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (52,'북촌동양문화박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5668&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌한옥마을이 자리한 북촌동양문화박물관에서는 설립자 권영두 과장이 30년 동안 수집 및 소장한 한국과 아시아 문화 예술품을 전시하고 있다.','03052 서울 종로구 북촌로11길 76',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (53,'서울약령시 한의약박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4632&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','우리나라 최대 한약 유통시장인 약령시에 있는 한의약 박물관','02570 서울 동대문구 약령중앙로 26 (제기동, 서울한방진흥센터) B2',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (54,'겸재정선미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1961&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','겸재정선미술관은 서울 강서구 양천로에 위치해 있으며 지하 1층, 지상 3층으로 이루어져 있다.','07522 서울 강서구 양천로47길 36 (가양동, 겸재정선미술관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (55,'토탈미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3085&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','토탈미술관에는 전시장, 미술관 아카데미, 자료실, 아트숍, 야외 공연장 등이 마련되어 있다.','03004 서울 종로구 평창32길 8',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (56,'남산서울타워','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36&fileTy=POSTTHUMB&fileNo=8&thumbTy=M','도심 속 로맨틱 아일랜드로 입지를 굳힌 남산서울타워는 예로부터 백년해로의 길지로 널리 알려진 남산(262m) 정상에 위치한 높이 236.7m의 탑으로, 해발 480m 위치에서 서울시를 360도 파노라마 뷰로 조망할 수 있는 최고의 전망을 자랑한다..','04340 서울 용산구 남산공원길 105 (용산동2가, YTN서울타워)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (57,'북촌한옥마을','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=261&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','600년 수도의 스펙트럼 속으로서울에서 가장 생생하게 살아 숨 쉬는 역사문화의 현장은 단연 북촌한옥마을이다. 600년 수도의 역사를 자랑하듯 전통 한옥들이 즐비한 동네다.','03059 서울 종로구 계동길 37 북촌문화센터 일대 (계동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (58,'서초관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11992&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서초관광정보센터는 문화와 예술이 자연과 함께 어우러져 있고, 패션, 뷰티와 비즈니스의 중심지인 강남역 9번 출구 뒤편에 위치해 있다.','06615 서울 서초구 강남대로 399 (서초동, 몬테소리)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (59,'덕수궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2049&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','덕수궁에 들어가기 위해 태평로의 상징인 대한문을 지난다. 하지만 원래의 위치는 아니다. 일제에 의해 태평로가 만들어지면서 덕수궁의 크기는 줄어들었고 대한문도 뒤쪽으로 물러났다.','04519 서울 중구 세종대로 99',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (60,'종묘','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=507&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','왕의 위패를 모시고 제를 올리는 종묘는 조선의 역사에 더없이 중요한 장소였다. 임금이 새로 왕위에 오르면 가장 먼저 종묘와 사직에 나아가 절을 하며 제사를 드렸다.','03135 서울 종로구 종로 157 (훈정동, 종묘공원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (61,'광화문광장 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16319&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인왕산 자락을 배경으로 600년을 내려온 서울 경관의 중심이자 우리 민족의 얼이 담긴 장소','03154 서울특별시 종로구 세종대로 172',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (62,'광화문광장','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1900&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','조선 태조는 1394년에 도읍을 한양으로 옮기고 정국인 경복궁을 지었다. 그리고 궁의 정문인 광화문 앞 길의 좌우에 의정부를 포함해 육조 관아 거리를 건설했다.','03154 서울특별시 종로구 세종대로 172',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (63,'흥인지문(동대문)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1999&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','한성부의 동쪽을 지키던 큰 대문보물 제1호 흥인지문(興仁之門)은 옛날 중요한 국가 시설이 있던 한성부를 보호하기 위해 만든 서울 성곽의 여덟 성문 가운데 동쪽의 큰 대문에 해당한다.','03119 서울 종로구 종로 288 (종로6가, 흥인지문)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (64,'숭례문(남대문)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=22888&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울 도성의 남쪽 정문이라서 통칭 남대문(南大門)이라고 불린다. 1395년(태조 4)에 짓기 시작하여 1398년(태조 7)에 완성되었고, 1447년(세종 29)에 개축하였다.','04528 서울 중구 세종대로 40 (숭례문(남대문))',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (65,'63스퀘어','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=252&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','여의도 63빌딩은 볼거리, 먹을거리, 즐길거리 등을 갖춘 복합 공간이다. 빌딩의 맨 꼭대기, 63 스카이텍은 전망 하나만으로 모든 걸 압도한다.','07345 서울 영등포구 63로 50 (여의도동, 63한화생명빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (66,'문화역서울 284','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=450&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','문화역서울284는 일제 강점기 당시 건축된 서울역사로 현재는 복합문화공간으로써 사용되고 있다.','04509 서울 중구 통일로 1 (서울역 본옥)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (67,'청와대','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5538&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울 종로구에 자리해 있는 청와대는 대한민국 대통령의 관저이다. 본관에는 대통령 집무실, 접견실, 회의실, 주거실 등이 있다.','03048 서울 종로구 청와대로 1 (세종로)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (14,'예술의 전당 한가람미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4325&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','한가람미술관은 예술의 전당 전면의 왼쪽에 위치해 있다.','06757 서울특별시 서초구 남부순환로 2406 (서초동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (15,'롯데월드타워','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=21278&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','글로벌 상징성과 한국의 전통미, 인간과 기술, 첨단과 자연이 공존하는 롯데월드타워는 하나의 건축물에 도시생활의 모든 것을 구현한 수직도시이다.','05551 서울 송파구 올림픽로 300 (신천동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (16,'창경궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=297&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','창경궁은 1483년 창덕궁 동쪽에 세워진 궁으로, 성종이 정희왕후, 안순왕후, 소혜왕후를 위해 수강궁을 확장하면서 창경궁이라는 이름을 붙였다.','03072 서울 종로구 창경궁로 185 (와룡동, 창경궁)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (17,'리움 미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1232&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','한남동 언덕길을 오르다 보면 리움 미술관과 만나게 된다. 삼성그룹의 창립자 고 이병철 회장의 수집품에서 출발한 미술관이다.','04348 서울 용산구 이태원로55길 60-16 (한남동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (18,'몽촌역사관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5507&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','올림픽공원 내에 위치한 몽촌역사관은 백제시대 대표적인 유적 들을 볼 수 있는 곳으로 몽촌토성과 풍납토성의 출토물도 전시하고 있다.','05540 서울 송파구 올림픽로 424 (몽촌역사관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (19,'삼청동 골목길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2121&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울에서 가장 스타일리시한 골목, 삼청동','서울특별시 종로구 가회동 일대',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (20,'서대문형무소역사관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1833&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서대문형무소는 현존하는 건축물 중 유일한 일본풍 목조 건물이다. 1923년 지은, 사형 선고를 받고 투옥된 전국의 애국지사들이 이감 후 생을 마감한 장소다.','03732 서울 서대문구 통일로 251 (현저동, 독립공원)',1);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (21,'서울역사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2723&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','2002년, 선사 시대부터 현대까지 서울의 역사와 문화를 정리하여 보여줄 서울역사박물관이 경희궁터에 문을 열었다.','03177 서울 종로구 새문안로 55 (신문로2가, 서울역사박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (22,'국립현대미술관 서울관 갤러리아트존','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16792&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국립현대미술관과 현대자동차의 협업으로 탄생한 갤러리 아트존은 문화상품 발굴, 차세대 작가들의 전시 및 상품제작 등을 통해 관람객들과의 보다 폭 넓은 소통의 장으로 예술의 문턱을 낮춰 문화저변을 확대해나가고 있다.','03062 서울 종로구 삼청로 30 (소격동) 국립현대미술관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (23,'국립현대미술관 서울관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11659&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','국립현대미술관 서울관은 민현준 건축가에 의해 설계되어 ''문화의 거리'' 삼청로에 2013년 11월 개관하였다.','03062 서울 종로구 삼청로 30 (소격동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (24,'서울 한양도성','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=90&fileTy=POSTTHUMB&fileNo=6&thumbTy=M','한양도성은 1396년 현재 서울의 도심부를 감싸고 있는 백악·낙타·목멱·인왕의 능선을 따라 처음 축조된 이후 여러 차례 개축되었다.','03098 서울 종로구 율곡로 283 (종로6가, 서울디자인지원센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (25,'경희대학교 중앙박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6927&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','경희대학교 중앙박물관은 경희대학교 부속 박물관으로 1955년 설립되었다.','02447 서울특별시 동대문구 경희대로 26 경희대학교 서울캠퍼스 중앙도서관 4층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (26,'서울중앙성원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4867&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','용산구 한남동에 있는 이슬람 서울중앙성원은 대한민국에 이슬람교와 아랍문화를 알리고, 이슬람 국가와의 원만한 교류를 위해 설립되었다.','04405 서울 용산구 우사단로10길 39',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (68,'국립고궁박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=20550&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국립고궁박물관은 500년 역사를 자랑하는 조선시대의 왕실 유물과 문화재를 전시한다.조선시대의 왕들이 직접 쓴 글씨와 시, 각종 유물들이 전시되어 있다.','03045 서울 종로구 효자로 12 (세종로, 국립고궁박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (69,'선정릉(선릉)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1414&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','삼릉공원 안에 성종과 정현왕후의 능인 선릉(宣陵)과, 아들 중종의 능 정릉(靖陵)이 있는 곳','06153 서울특별시 강남구 선릉로100길 1 (삼성동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (70,'운현궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=471&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','운현궁은 조선 후기 흥선대원군의 사가이다. 흥선대원군의 둘째 아들 고종이 출생하여 왕위에 오르기 전까지 성장한 곳이다.','03131 서울 종로구 삼일대로 464 (운현궁)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (71,'서울시립미술관 (서소문본관)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1525&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','덕수궁 돌담길 옆 아름다운 미술관운치 있는 덕수궁 돌담길을 서서히 돌아 정동길로 접어들면 왼쪽으로 오래된 수목과 꽃들이 어우러진 아름다운 야외 정원이 시선을 잡아끈다.','04515 서울 중구 덕수궁길 61 (서소문동, 서울시립미술관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (72,'서울광장','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1539&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울에서 신발을 벗고 걸을 수 있는 곳. 따스한 햇살을 이불 삼아 낮잠을 청할 수 있는 곳. 바로 서울광장이다.','100-101 서울특별시 중구 세종대로 110 (태평로1가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (73,'대한민국역사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6668&fileTy=POSTTHUMB&fileNo=4&thumbTy=M','대한민국역사박물관은 19세기 말 개항기부터 오늘날에 이르는 대한민국의 역사를 종합적, 체계적으로 보여주는 국내 최초의 국립 근현대사박물관이다.','03141 서울시 종로구 세종대로 198 (세종로)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (74,'경희궁','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1159&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','경희궁은 본래 인조의 아버지인 정원군의 집이었으나, 그 터에 왕기가 서려 있다는 말이 돌자 광해군이 이를 몰수해 궁궐을 지었다.','03177 서울 종로구 새문안로 45 (경희궁)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (150,'서울역사박물관 온라인 교육 서비스','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=33743&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','"언제 어디서나 만날 수 있는 박물관" 서울역사박물관 온라인 교육 서비스','03177 서울 종로구 새문안로 55 (신문로2가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (151,'용산공예관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=33266&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','공예문화의 과거와 현재, 도시와 도시를 이어주는 네트워크 플랫폼 : 용산공예관','04399 서울 용산구 이태원로 274 (한남동, 용산전통공예문화체험관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (152,'서울특별시청서소문별관정동전망대','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32889&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','정동전망대라고도 불리는 서울특별시청서소문별관정동전망대에서는 아름다운 덕수궁의 모습을 한눈에 볼 수 있는 곳이다.','04515 서울 중구 덕수궁길 15 (서소문동, 서울시청 서소문별관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (153,'안녕인사동','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32734&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','안녕인사동은 어제, 오늘, 내일을 잇는 공간을 담아 추억과 즐거움을 선사하는 문화복합몰이다.','03145 서울 종로구 인사동길 49 (관훈동) 안녕인사동',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (154,'대림시장 감자국거리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32546&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','응암동에 위치한 대림시장 감자국거리는 1980년대 중반 이후 대림시장에 자리 잡고 있던 식당들이 돼지 등뼈와 감자, 우거지 등을 넣고 끓인 감자국을 팔기 시작하면서 감자국거리가 형성되었다. 현재는 응암동의 명소로 많은 사랑을 받고 있다.','03351 서울 은평구 통일로78길 22-11 (스카이힐튼) 대림시장 감자국거리',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (155,'정동1928 아트센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32529&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','정동1928 아트센터는 1928년에 구세군 사관양성 및 선교와 사회사업을 위한 본부로 이용하기 위한 건축물로 완공되었다.','04519 서울 중구 덕수궁길 130 (정동, 구세군중앙회관) 정동1928 아트센터',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (156,'형제대장간','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=32528&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','수색역에서 도보 5분 거리에 위치한 40여 년의 세월의 역사가 살아 숨 쉬는 형제대장간은 형제가 함께 운영하고 있으며, 농기구, 건축 기구뿐 아니라 모든 품목을 생산한다.','03504 서울 은평구 수색로 249 (수색동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (157,'서소문성지역사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=30804&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서소문성지역사박물관은 조선 후기 한국 교회사를 한눈에 살펴볼 수 있는 역사박물관이다.','04510 서울 중구 칠패로 5 (의주로2가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (158,'아모레퍼시픽미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=30803&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','아모레퍼시픽 미술관은 서울시 용산의 아모레퍼시픽 신본사에 새롭게 문을 연 미술관이다.','04386 서울 용산구 한강대로 100 (한강로2가, 아모레퍼시픽)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (159,'황학정','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29766&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','황학정은 국민들의 심신단련을 위해 궁술은 장려되어야 한다고 생각하는 고종황제의 뜻에 따라 지어진 유서 깊은 활터이다.','03027 서울 종로구 사직로9길 15-32 (사직동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (160,'용산방앗간','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29722&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','용산구 이촌동 철길 부근에서 30년 이상 영업 중인 용산방앗간은 오랜 시간 떡공장에서 일한 사장님이 노하우를 바탕으로 차린 떡집이다.','04380 서울 용산구 이촌로29길 31 (한강로3가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (161,'성우이용원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29716&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1927년 개원한 성우이용원은 옛 모습을 그대로 간직해 ''서울미래유산''으로 지정된 이발소이다.','04183 서울 마포구 효창원로97길 4-1 (공덕동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (162,'개미슈퍼','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29715&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울역 뒤편 골목길에 위치한 개미슈퍼는 오랜 세월을 고스란히 간직한 자그마한 구멍가게이다.','04303 서울 용산구 청파로85길 33 (서계동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (163,'쉼박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29578&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','쉼박물관은 잊혀져 가는 문화를 보존하고 현대 문화예술과 접목시켜 새로운 문화를 만들고자 하는 박물관이다.','03015 서울 종로구 세검정로 209-17 (쉼박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (164,'아라아트센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24613&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인사동에 위치하는 아라아트센터는 기획 전시 공간에 대한 바람에서 고안된 곳이다.','03145 서울 종로구 인사동9길 26 (견지동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (165,'아라아트센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24613&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인사동에 위치하는 아라아트센터는 기획 전시 공간에 대한 바람에서 고안된 곳이다.','03145 서울 종로구 인사동9길 26 (견지동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (166,'aT센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29561&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','aT센터는 국제적인 전시, 컨벤션과 무역 비즈니스가 한 곳에서 이루어지는 새로운 스타일의 전시, 컨벤션센터이다.','06774 서울 서초구 강남대로 27 (양재동, AT센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (167,'절두산순교성지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29394&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1866년 병인박해 때 순교한 천주교인의 신앙과 얼을 널리 알리기 위하여 서울 마포구에 1967년 10월 절두산순교기념관으로 개관한 뒤 한국천주교순교자박물관으로 이름을 바꾸었다.','04085 서울 마포구 토정로 6 (합정동, 한국천주교순교자박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (168,'돈의문역사관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29381&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','돈의문전시관은 새문안 동네의 식당으로 운영되던 건물들을 활용하여 새롭게 조성한 문화공간이다.','03178 서울 종로구 새문안로 35-54 (신문로2가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (169,'서울메트로미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=29238&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울메트로미술관은 지하철 3호선 경복궁역 내에 위치한 시민을 위한 문화 공간이다.','03170 서울 종로구 사직로 지하 130 (적선동, 3호선 경복궁역)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (170,'백범광장공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28656&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','백범광장공원은 서울 중구 회현동 남산공원을 올라가는 도중 산 중턱에 위치한다.','04633 서울 중구 퇴계로8길 49-4',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (117,'초전섬유퀼트박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6465&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','초전섬유퀼트박물관은 1998년에 설립된 섬유 및 퀼트 작품을 전시하는 박물관이다.','04630 서울 중구 퇴계로18길 66 (제일빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (118,'잠실대교','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=41095&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울특별시 광진구 자양동과 송파구 잠실동 27번지 사이에 위치한 한강에 건설한 서울의 6번째 다리. 잠실동과 연결되는 다리라 잠실대교라고 하였다.','05502 서울 송파구 한가람로 65 (잠실동, 한강사업본부 잠실안내센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (119,'용산공원 부분개방부지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=40795&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','과거 미군 장교숙소로 활용되던 부지로 조선시대 얼음을 저장하던 서빙고가 인근에 있어 조선 초부터 ‘서빙고’로 불렸던 곳이다.','04383 서울 용산구 서빙고로 221 (용산동6가, 미군 장교숙소5단지)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (120,'국립기상박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=40770&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','조선시대부터 근현대까지 우리나라 기상문화를 연구하고, 보존하는 국내 최초 기상과학역사 박물관입니다. 서양보다 200여년 앞서 발명된, 세계에서 현존하는 유일한 측우기 ‘공주 충청감영 측우기(公州 忠淸監營 測雨器)’를 소장하고 있습니다.','03178 서울 종로구 송월길 52 (송월동, 국립기상박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (121,'춘당지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=39708&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','창경궁 내에 있는 아름다운 춘당지','03072 서울 종로구 창경궁로 185 (와룡동, 창경궁)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (122,'가을단풍길(월드컵로)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38858&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','난지천공원을 따라 쭉 펼쳐지는 월드컵로 가을단풍길','03906 서울 마포구 월드컵로42길 9-1 (가로판매대07)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (141,'남산케이블카','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35015&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','남산의 풍광을 한눈에 조망할 수 있는 남산케이블카','04630 서울 중구 소파로 83 (회현동1가, 남산케이블카)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (142,'전태일기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34860&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','전태일 열사를 기념하며 시민 모두가 노동의 가치를 깨닫고 그 의미를 배우는 공간','03191 서울 종로구 청계천로 105 (관수동, 전태일기념관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (143,'용산공원갤러리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34859&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','일제강점기부터 역사의 공유, 그리고 미국과의 공존까지','04322 서울 용산구 한강대로 237',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (144,'서울기록원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34857&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울의 시정기록과 시민기록을 수집하는 서울의 대표 문화기관','03371 서울 은평구 통일로62길 7 (녹번동, 서울기록원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (145,'셋이서문학관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34420&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','문학작품 전시 및 문화체험 공간','03308 서울시 은평구 진관길 23 셋이서문학관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (146,'서울도시건축전시관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=34149&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','시민들이 도심 내 휴식을 향유하는 동시에 도시, 건축에 관심있는 모든 국내외인들에게 관련 자료를 공유하고 관련 전시 및 행사를 체험하는 곳입니다.','04519 서울 중구 세종대로 119 (태평로1가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (232,'대구참기름집','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27468&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌에 위치한 이제는 보기 힘든 기름집이다.','03056 서울 종로구 계동길 67 (계동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (250,'서울역관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27194&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울역관광정보센터는 서울역에 위치한 관광정보센터로 내·외국인 관광객들의 편의를 위해 설립되었다.','04320 서울 용산구 한강대로 405 (동자동, 서울역(철도역)) 지상2층 안내데스크',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (251,'송파관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27193&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','송파관광정보센터는 내·외국인 관광객의 편의를 위해 설립되었다.','05617 서울 송파구 잠실로 180 (신천동, 송파관광정보센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (252,'영등포관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27191&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','영등포관광정보센터는 서울 서남권 중심거점이자 하루 수십만의 유동인구가 지나고 있는 타임스퀘어 광장에 2017년 9월 개관했다.','07305 서울 영등포구 영중로 15 (영등포동4가, 타임스퀘어)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (253,'송파관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27193&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','송파관광정보센터는 내·외국인 관광객의 편의를 위해 설립되었다.','05617 서울 송파구 잠실로 180 (신천동, 송파관광정보센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (233,'이음피움 봉제역사관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27380&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','이음피움 봉제역사관은 동대문 패션타운의 배후생산기지인 창신동에 자리 잡고 있으며, 우리의 삶과 함께 해온 봉제 산업을 다양한 관점에서 조망하는 도심 속 문화역사공간입니다.','03097 서울 종로구 창신4가길 26 (창신동, 이음피움 봉제역사관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (234,'삼청로 안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27232&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','삼청동에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','03053 서울 종로구 삼청로 68 (안송빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (235,'신촌역사 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27231&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','신촌 구역사에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','03765 서울 서대문구 신촌역로 30 (신촌동, 신촌민자역사) 신촌역사 내',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (171,'연세대 캠퍼스','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28340&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','연세대 캠퍼스는 외관이 아름다워 영화나 드라마에도 자주 등장한다.','03722 서울 서대문구 연세로 50 (신촌동, 연세대학교)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (172,'봉원사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28339&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','봉원사는 신라 진성여왕 3년(889년)에 현 연세대 터에 창건한 절로, 조선 영조 24년(1748년) 때 지금의 터전으로 이전했다.','03721 서울 서대문구 봉원사길 120 (봉원사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (173,'봉원사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28339&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','봉원사는 신라 진성여왕 3년(889년)에 현 연세대 터에 창건한 절로, 조선 영조 24년(1748년) 때 지금의 터전으로 이전했다.','03721 서울 서대문구 봉원사길 120 (봉원사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (174,'ECC(Ewha Campus Complex)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28338&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','ECC(Ewha Campus Complex)는 이화여자대학교 캠퍼스 내에 조성한 복합 단지다.','03760 서울 서대문구 이화여대길 52 (대현동, 이화여자대학교)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (175,'송월동 일대','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=10567&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종로구 송월동 일대에는 덕수궁, 서울역사박물관, 경희궁, 숭례문, 서대문형무소역사관, 독립문 등 대한민국의 다양한 역사적 유적지들이 위치해 있다.','110-101 서울특별시 종로구 송월동 일대',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (176,'대오서점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=10929&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울에서 가장 오래된 서점으로 알려진 대오서점은 경복궁역에서 약 5분 거리에 위치해 있다.','03036 서울특별시 종로구 자하문로7길 55 (누하동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (177,'오보코 갤러리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=10946&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','복합적 문화공간인 오보코(OVOCO) 갤러리에서는 주얼리 전시를 비롯해 미술, 음악, 아카데미 등 다양한 문화행사가 이뤄지고 있다.','02837 서울특별시 성북구 선잠로5길 15 (성북동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (178,'흑석동 효사길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11115&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','흑석동 효사길은 대한민국 60~70년대의 분위기를 담고 있는 과거와 현재가 공존하는 곳으로 드라마의 촬영지로 화제가 되기도 했다.','06910 서울 동작구 흑석동 효사 4, 5길',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (179,'디지털미디어시티','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11144&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','디지털미디어시티는 마포구에 위치한 IT 및 미디어 산업클러스터로 국내 대기업 사옥들이 입주를 하며 급격히 발전해가고 있다.','서울특별시 마포구 월드컵북로 366 (상암동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (180,'김포공항관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11839&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','김포공항 국제선 입국장 내 자리한 김포공항관광정보센터는 국제선 청사 1층에 위치해 있다.','07505 서울 강서구 하늘길 38 (방화동, 김포공항(국제청사))',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (181,'디지털미디어시티','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11144&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','디지털미디어시티는 마포구에 위치한 IT 및 미디어 산업클러스터로 국내 대기업 사옥들이 입주를 하며 급격히 발전해가고 있다.','서울특별시 마포구 월드컵북로 366 (상암동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (182,'김포공항관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11839&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','김포공항 국제선 입국장 내 자리한 김포공항관광정보센터는 국제선 청사 1층에 위치해 있다.','07505 서울 강서구 하늘길 38 (방화동, 김포공항(국제청사))',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (183,'인천국제공항 서울관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=11864&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인천국제공항 서편과 동편에 위치한 인천국제공항 서울관광정보센터는 한국을 방문하는 해외 여행객들을 위해 연중무휴 열려있다.','22382 인천 중구 공항로 272 (운서동, 인천국제공항여객터미널)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (185,'피규어뮤지엄W','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=15863&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','피규어뮤지엄W는 다양한 종류의 피규어들과 장난감들이 전시된 박물관이다.','06014 서울 강남구 선릉로158길 3 (청담동, Ys Roo)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (186,'서울의료관광 헬프데스크','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=15966&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울의료관광 헬프데스크는 외국인 환자를 위한 편의를 제공하기 위해 올해 오픈했다. 의료관광을 위해 한국을 방문한 외국인 환자에게 서울 의료 기관과 관련된 정보를 제공한다.','04537 서울 중구 퇴계로 131 (충무로2가, 신일빌딩) 2층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (187,'위안부 ''기억의 터''','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=19540&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','‘기억의 터’는 위안부 피해자 할머니들을 기리는 추모공원이다.','04628 서울 중구 퇴계로26가길 6 (예장동) 서울종합방재센터',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (188,'성균관대학교','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=19656&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','성균관대학교는 서울 종로구에 위치한 인문사회과학캠퍼스와 경기도 수원시에 위치한 자연과학캠퍼스로 나뉘어 운영되고 있다.','03063 서울 종로구 성균관로 25-2 (명륜3가, 성균관대학교)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (189,'피규어뮤지엄W','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=15863&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','피규어뮤지엄W는 다양한 종류의 피규어들과 장난감들이 전시된 박물관이다.','06014 서울 강남구 선릉로158길 3 (청담동, Ys Roo)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (207,'돈의문 터(옛 서대문)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23759&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','돈의문은 서울 도성의 서쪽 문으로, 흔히 ‘서대문’이라고 불린다.1915년 3월 도로 확장공사를 위해 철거되었다.','110102 서울 종로구 평동 112',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (208,'숙정문','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23760&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울성곽을 이루는 사대문(四大門) 가운데 하나로, 도성의 북쪽 대문이다. 1963년 1월 21일 서울성곽에 포함되어 사적 제10호로 지정되었다','02822 서울 성북구 대사관로 1 (성북동, 홍련사(조계종))',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (209,'돈의문 박물관마을','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23761&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','돈의문 터 근처의 돈의문 박물관 마을은 근현대에 조성되었던 골목길과 주택들을 활용한 공간으로 새롭게 조성한 서울의 새 명소다.','03178 서울 종로구 송월길 14-3 (신문로2가, 국도빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (210,'서울중앙우체국','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24591&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울의 중심부인 명동에 위치한 서울중앙우체국은 스카이홀의 해외 비즈니스 고객에 알맞은 동시통역뿐만 아니라, 다목적용으로 쓸 수 있는 편안하고 효율적인 회의장과 리셉션홀도 제공하고 있다.','04535 서울 중구 소공로 70 (충무로1가, 서울중앙우체국청사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (211,'홍익문고','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28332&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1957년에 개업한 홍익문고는 서울에서 영업하고 있는 서점 중 가장 오래된 곳이다.','03779 서울 서대문구 연세로 2 (창천동, 홍익문고)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (212,'미도사진관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28331&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서대문구에 위치한 미도사진관은 다른 사진관에서는 볼 수 없는 특별한 렌즈가 있다.','03789 서울 서대문구 신촌로 75 (창천동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (213,'돈의문 박물관마을','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23761&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','돈의문 터 근처의 돈의문 박물관 마을은 근현대에 조성되었던 골목길과 주택들을 활용한 공간으로 새롭게 조성한 서울의 새 명소다.','03178 서울 종로구 송월길 14-3 (신문로2가, 국도빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (214,'서울중앙우체국','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24591&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울의 중심부인 명동에 위치한 서울중앙우체국은 스카이홀의 해외 비즈니스 고객에 알맞은 동시통역뿐만 아니라, 다목적용으로 쓸 수 있는 편안하고 효율적인 회의장과 리셉션홀도 제공하고 있다.','04535 서울 중구 소공로 70 (충무로1가, 서울중앙우체국청사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (215,'홍익문고','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28332&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1957년에 개업한 홍익문고는 서울에서 영업하고 있는 서점 중 가장 오래된 곳이다.','03779 서울 서대문구 연세로 2 (창천동, 홍익문고)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (216,'미도사진관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28331&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서대문구에 위치한 미도사진관은 다른 사진관에서는 볼 수 없는 특별한 렌즈가 있다.','03789 서울 서대문구 신촌로 75 (창천동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (217,'춘추사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28328&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','춘추사는 3대째 내려오고 있는 60년 전통의 가운 전문점이다.','03767 서울 서대문구 이화여대8길 10 (대현동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (218,'연희사진관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28327&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1950년대에 개업한 연희사진관은 3대에 걸쳐 65년이 넘는 세월 동안 이어지고 있는 사진관이다.','03766 서울 서대문구 신촌로 175 (대현동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (219,'해창양복점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28057&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','해창양복점은 90년 역사를 가진 소공동에서 가장 오래된 맞춤 양복점이다.','04532 서울 중구 남대문로7길 33 (소공동) 소공빌딩 101호',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (220,'글벗서점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28052&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','신촌에 위치한 글벗서점은 1979년에 개업한 헌책방으로 다양한 서적을 보유하고 있다.','04056 서울 마포구 신촌로 48 (동교동) 지층, 1층, 2층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (221,'글벗서점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28052&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','신촌에 위치한 글벗서점은 1979년에 개업한 헌책방으로 다양한 서적을 보유하고 있다.','04056 서울 마포구 신촌로 48 (동교동) 지층, 1층, 2층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (222,'호미화방','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=28051&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1975년에 개업한 호미화방은 홍대 앞 대표적 화방이다.','04039 서울 마포구 홍익로3길 20 (서교동, 서교오피스텔)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (223,'유일한의원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27814&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','유일한의원은 이름부터 오로지 유(唯), 하나 일(一)이라는 뜻을 품는다.','03124 서울 종로구 율곡로30길 17-3 (종로6가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (224,'서울음악사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27475&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1972년에 개업한 서울음악사는 서울시청 지하도 상가에 자리하고 있다.','04533 서울 중구 을지로 지하 12 (을지로1가, 시청광장지하쇼핑센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (263,'공평도시유적전시관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26675&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','땅 속에 묻혀 있던 조선 초기~일제 강점기 600년 역사를 한눈에 볼 수 있는 이 서울 종로 공평동에 개관했다.','03161 서울 종로구 우정국로 26 (센트로폴리스 지하 1층)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (264,'별마당 도서관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26558&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','코엑스몰 중심에 위치한 별마당 도서관은 휴식과 만남, 그리고 책을 주제로 소통하는 문화 감성 공간으로써 누구나 무료로 이용할 수 있도록 모두에게 열려있다.','06164 서울 강남구 영동대로 513 (삼성동, 코엑스)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (265,'동대문역사관 상설전시실 재개관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26206&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','옛 동대문운동장 부지의 역사를 한눈에 볼 수 있는 상설전시','04566 서울 중구 을지로 281 (을지로7가, 2-1) 동대문역사공원 내 동대문역사관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (266,'통인가게','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=25931&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','통인가게는 1924년에 개업해서 93년 동안 줄곧 우리 문화와 예술을 내외국인들에게 알리고 보급하는 일을 해왔다.','03148 서울 종로구 인사동길 32 (관훈동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (125,'국립항공박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=38021&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국립항공박물관은 서울시 강서구 김포공항 부지에 위치한 항공 분야 최초의 국립박물관으로서 항공의 과거, 현재, 미래를 한 번에 느낄 수 있는 다양한 전시와 체험관으로 구성되어있다.','07505 서울 강서구 하늘길 177 (공항동, 국립항공박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (126,'아쿠아플라넷63','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37891&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','다양한 해양생물과 아쿠아 퍼포먼스를 함께 즐길 수 있는 아쿠아리움','07345 서울 영등포구 63로 50 (여의도동, 63한화생명빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (127,'세운청계상가','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37890&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1960년대 주상복합건물로 지어진 세운청계상가는 드라마 빈센조의 금가프라자로 등장을 하며 많은 사람들이 방문하는 핫플레이스로 자리 잡았다.','04545 서울 중구 청계천로 160 (산림동, 세운청계상가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (128,'HYBE INSIGHT (하이브 뮤지엄)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37879&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','하이브의 뮤지엄 HYBE INSIGHT(하이브 인사이트)는 ‘We believe in Music’이라는 하이브의 미션 아래 ‘음악으로 감동을 전하고 선한 영향력을 나누며 삶의 변화를 만들어 간다’는 하이브의 지향점이 녹아 있는 복합문화공간이다. 하이브의 아티스트와 팬이 음악을 매개로 만나는 공간이며, 음악을 사랑하는 누구나 즐길 수 있도록 설계됐다.','04389 서울 용산구 한강대로 42 (한강로3가, 용산트레이드센터) 하이브 인사이트 지하 1, 2층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (129,'서울관광플라자 관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37583&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종로구 삼일빌딩에 위치한 서울관광플라자 관광정보센터는 서울의 모든 관광정보를 얻을 수 있는 열린 공간으로 한국어, 영어, 중국어, 일본어로 관광안내 서비스를 제공한다.','03190 서울 종로구 청계천로 85 (관철동, 삼일빌딩)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (130,'창경궁 대온실','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37176&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','창경궁 내부에 위치한 대한민국 최초의 대온실','03072 서울 종로구 창경궁로 185 (와룡동, 창경궁)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (131,'석파정','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37164&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','조선시대 권력자들이 사랑한 정원','03021 서울 종로구 창의문로11길 4-1',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (132,'자하문터널','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37158&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','영화 기생충에 나왔던 터널','서울 종로구 청운동',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (133,'일자산허브천문공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37130&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','24시간 이용 가능한 천문대가 있는 허브 공원','134-060 서울 강동구 둔촌동 산86',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (134,'KCDF갤러리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37044&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','공예전시를 즐길 수 있는 복합문화공간','03145 서울 종로구 인사동11길 8 (관훈동, 공예종합유통지원센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (135,'익선동 한옥거리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=37008&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','연인들이 많이 찾는 종로의 랜드마크 거리','03133 서울 종로구 돈화문로11가길 17 (익선동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (136,'금선사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36843&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북한산자락에 위치한 아름다운 절','03000 서울 종로구 비봉길 137 (구기동, 금선사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (137,'스마트서울 전시관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=36048&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','시민의 삶을 변화시키고 스마트 도시 기술과 서비스를 직접 알아보는 스마트서울의 모습을 확인하실 수 있습니다.','04524 서울 중구 세종대로 110 (태평로1가, 서울특별시청) B1',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (138,'은평한옥마을','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35673&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북한산 자락, 은평구 진관동에 위치한 그림 같은 한옥마을','03308 서울 은평구 연서로50길 8 (진관동, 은평역사한옥박물관) 은평한옥마을',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (139,'국립한글박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35405&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','국립한글박물관은 한글과 한글문화 가치의 보존, 확산, 재창조를 위해 설립된 공간이다.','04383 서울 용산구 서빙고로 139 (용산동6가, 국립한글박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (140,'서울로7017 여행자터미널','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=35078&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울로7017 여행자터미널은 잘생겼다 서울 31을 거점으로 맞춤형 서울 여행코스를 제안한다','04528 서울 중구 만리동1가 22-1 서울로7017 여행자터미널',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (190,'서울의료관광 헬프데스크','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=15966&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울의료관광 헬프데스크는 외국인 환자를 위한 편의를 제공하기 위해 올해 오픈했다. 의료관광을 위해 한국을 방문한 외국인 환자에게 서울 의료 기관과 관련된 정보를 제공한다.','04537 서울 중구 퇴계로 131 (충무로2가, 신일빌딩) 2층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (191,'위안부 ''기억의 터''','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=19540&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','‘기억의 터’는 위안부 피해자 할머니들을 기리는 추모공원이다.','04628 서울 중구 퇴계로26가길 6 (예장동) 서울종합방재센터',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (192,'성균관대학교','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=19656&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','성균관대학교는 서울 종로구에 위치한 인문사회과학캠퍼스와 경기도 수원시에 위치한 자연과학캠퍼스로 나뉘어 운영되고 있다.','03063 서울 종로구 성균관로 25-2 (명륜3가, 성균관대학교)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (193,'스튜디오 콘크리트','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=20193&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','스크린과 브라운관을 넘나들며 명품 연기로 사랑받고 있는 유아인은 1980년대 출생의 아티스트들이 모인 창작 집단 ‘스튜디오 콘크리트’를 이끌고 있다.','04417 서울 용산구 한남대로 162 (한남동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (194,'경찰박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=20549&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국민과 경찰이 함께하는 역사와 체험의 복합문화공간','03178 서울 종로구 새문안로 41 (신문로2가, 경찰박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (195,'백인제가옥','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=21128&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌 가회동에 위치한 백인제 가옥은 근대 한옥의 양식을 고스란히 보존하고 있는 대표적인 일제강점기 한옥이다.','03055 서울 종로구 북촌로7길 16 (가회동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (196,'서울로7017','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23496&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','6개 구역을 잇는 공중보행로의 기능과 녹지광장을 결합하는 살아있는 식물도감이자 1km 도심전망대이다.','04509 서울 중구 청파로 432 (봉래동2가, 코레일서울본부)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (197,'백인제가옥','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=21128&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌 가회동에 위치한 백인제 가옥은 근대 한옥의 양식을 고스란히 보존하고 있는 대표적인 일제강점기 한옥이다.','03055 서울 종로구 북촌로7길 16 (가회동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (198,'서울로7017','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23496&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','6개 구역을 잇는 공중보행로의 기능과 녹지광장을 결합하는 살아있는 식물도감이자 1km 도심전망대이다.','04509 서울 중구 청파로 432 (봉래동2가, 코레일서울본부)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (199,'SeMA 벙커','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23532&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울시립미술관은 한국 근현대 군사문화의 상징시설이자 서울시 미래유산인 여의도 지하벙커를 활용하여 여의도에 특화된 복합문화예술공간 SeMA 벙커로 새롭게 선보인다.','07327 서울 영등포구 의사당대로 지하 101 (여의도역)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (200,'세운상가','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23561&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','세운전자상가는 1968년 세계의 기운이 모이다 라는 뜻을 가진 국내 최초의 종합전자상가이자 40년 전통의 전자상가','03194 서울 종로구 청계천로 159 (장사동, 세운상가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (201,'덕수궁돌담길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23563&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','기존의 도로를 보행자 중심의 도로로 재정비하고, 보행자를 위해 보도와 차도 공존도로 및 푸르름이 가득한 가로공간인 녹도의 개념을 복합적으로 도입한 우리나라 최초의 사례로 길이는 900m이다.','04519 서울 중구 세종대로19길 24 (정동, 영국대사관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (202,'혜화문','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23606&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','1397년(태조 5) 도성을 에워싸는 성곽을 쌓을 때 도성의 북동방에 설치한 문(門)이다.','03076 서울 종로구 창경궁로 307 (혜화동, 혜화문)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (203,'서울시립과학관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23629&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울시립과학관은 서울시가 청소년의 기초과학 이해를 돕고 과학의 대중화를 위해 건립한 최초의 시립과학관이다.','01792 서울 노원구 한글비석로 160 (하계동, 서울시립과학관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (204,'소덕문 터(옛 서소문)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23758&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','소덕문은 도성의 서남쪽인 숭례문과 돈의문의 중간지점에 있었다. 도성의 4개의 소문(小門) 중 하나로서 태조 5년에 다른 성문들과 함께 건설되었다.','04513 서울 중구 서소문로 100 (중앙일보 구관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (205,'서울시립과학관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23629&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울시립과학관은 서울시가 청소년의 기초과학 이해를 돕고 과학의 대중화를 위해 건립한 최초의 시립과학관이다.','01792 서울 노원구 한글비석로 160 (하계동, 서울시립과학관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (206,'소덕문 터(옛 서소문)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23758&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','소덕문은 도성의 서남쪽인 숭례문과 돈의문의 중간지점에 있었다. 도성의 4개의 소문(小門) 중 하나로서 태조 5년에 다른 성문들과 함께 건설되었다.','04513 서울 중구 서소문로 100 (중앙일보 구관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (225,'서울상회','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27474&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울상회는 외국인들이 선호하는 김, 홍삼, 송이버섯 등을 파는 곳이다.','04528 서울 중구 남대문시장4길 2 (남창동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (226,'돌 레코드','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27472&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','돌 레코드는 1975년부터 지금까지 누군가의 추억이 담긴 LP판, CD, 테이프를 판매하는 음반가게이다.','04571 서울 중구 마장로9길 49-29 (황학동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (227,'삼보원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27471&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','조계사 앞에 위치한 삼보원은 43년째 불교용품을 판매하는 가게이다.','03144 서울 종로구 우정국로 53 (견지동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (228,'대구참기름집','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27468&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌에 위치한 이제는 보기 힘든 기름집이다.','03056 서울 종로구 계동길 67 (계동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (229,'서울상회','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27474&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','서울상회는 외국인들이 선호하는 김, 홍삼, 송이버섯 등을 파는 곳이다.','04528 서울 중구 남대문시장4길 2 (남창동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (230,'돌 레코드','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27472&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','돌 레코드는 1975년부터 지금까지 누군가의 추억이 담긴 LP판, CD, 테이프를 판매하는 음반가게이다.','04571 서울 중구 마장로9길 49-29 (황학동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (231,'삼보원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27471&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','조계사 앞에 위치한 삼보원은 43년째 불교용품을 판매하는 가게이다.','03144 서울 종로구 우정국로 53 (견지동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (94,'정동제일교회','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2134&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','1885년 미국인 목사 아펜젤러가 마련한 정동제일교회는 한국 최초의 프로테스탄트 교회 건축물이자 한국 기독교대한감리회의 대표적인 교회이다.','04516 서울특별시 중구 정동길 46 (정동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (95,'성곡미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1910&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','성곡미술관은 쌍용그룹 창업자 성곡 김성곤을 기념하여 그의 저택 자리에 건립되었다.','03175 서울 종로구 경희궁길 42 (신문로2가, 성곡미술관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (96,'사직단','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1826&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종로구 사직동에 있는 사직단은 조선 당시 토지신과 곡물신에게 풍년을 기원하며 제사를 드리기 위해 쌓은 제단이다.','03027 서울 종로구 사직로9길 5 (사직단)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (97,'태릉, 강릉','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2299&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','태릉과 강릉은 서울 노원구 화랑로에 위치한 조선시대 왕릉으로 태릉과 강릉 중간 지역엔 대한체육회에서 운영하는 태릉선수촌이 있다.','01794 서울 노원구 화랑로 681 (공릉동, 태강릉)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (98,'손기정기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6996&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','손기정기념관은 손기정 선수의 뜻을 기리기 위해 손기정 선수의 모교인 양정의숙을 고쳐 그의 탄생 100주년인 2012년에 개관하였다.','04501 서울 중구 손기정로 101 (손기정 체육공원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (99,'일민미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2252&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','일민미술관은 일민 김상만을 기념하여 1996년에 세운 미술관으로 종로구 세종로에 위치해있다.','03187 서울 종로구 세종대로 152 (세종로, 일민미술관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (100,'정동길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=889&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','정동길에 붙는 수식어들이 몇 개 있다. 서울에 몇 안 남은 고풍스러운, 인사동이나 삼청동처럼 사람으로 들끓지 않고 여유로운 분위기를 잘 지킨, 산책하기 좋은, 문화적 냄새가 물씬 풍기는, 장사꾼들의 야단스러움으로부터 해방될 수 있는 유일한 동네, 가로수가 예쁜 거리 등등. 모두 맞는 말이다.','04516 서울 중구 정동길 2 (충정로1가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (101,'대각사','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5018&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','창덕궁 후원 앞에 위치한 대각사는 1911년 창건되었다.','03134 서울 종로구 율곡로10길 87 (대각사)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (102,'아트선재센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2406&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','아트선재센터는 경주시에 있는 선재미술관의 분관','03062 서울 종로구 율곡로3길 87 (소격동, 아트선재센타)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (103,'경교장','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1151&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','경교장은 대한민국 임시정부의 주석이었던 백범 김구(金九)가 사용했던 개인 사저로 서울 종로구에 있다.','03181 서울 종로구 새문안로 29 (경교장)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (104,'춘원당 한의약박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2637&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','2008년 개관한 춘원당 한방박물관은 탕전실, 품질검사실 및 문화공간, 진료실, 치료실 등으로 총 지하 1층, 지상 6층으로 이뤄져 있다.','03139 서울 종로구 돈화문로9길 27 (춘원당한방박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (105,'만해한용운 심우장','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=1399&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','성북동 꼭대기 북향 집서울 성북구 성북동에는 문화유산이 많다. 한성대역 입구에서 삼청각 방향으로 걷다 보면 길의 좌우로 수많은 역사 유적들이 얼굴을 내민다.','02879 서울 성북구 성북로29길 24 (만해 한용운 심우장)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (106,'의릉','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=5208&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','성북구 석관동 한국예술종합학교 내부에 자리해 있는 조선 20대 왕 경종과 선의왕후의 무덤인 의릉은 일반적으로 나란히 놓이는 쌍릉과 달리 왕과 왕비의 능이 앞뒤로 배치돼 있다.','02789 서울 성북구 화랑로32길 146-37 (의릉)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (107,'경희대학교 자연사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=6957&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','1978년에 지어진 경희대학교 자연사박물관은 경희대학교에서 설립하고 운영하는 박물관','02447 서울특별시 동대문구 경희대로 26 자연사박물관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (108,'영휘원 숭인원(홍릉)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4525&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','청량리동에 위치한 조선 제26대 왕 고종 후비 선헌귀비 엄씨의 묘소인 영휘원은 1991년 사적 제361호로 지정되었다.','02456 서울 동대문구 홍릉로 90 (영휘원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (109,'반포대교 야경','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=16325&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','반포대교는 용산구와 서초구를 잇는 2층 교량으로 무지개 분수 쇼와 여의도 불꽃축제 기간에는 불꽃놀이를 구경할 수 있는 곳이다.','06500 서울 서초구 올림픽대로 2085-14',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (110,'암사동 선사주거지','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2175&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','우리나라의 대표적인 신석기시대 유적인 암사동 선사 유적지에서는 기원전 5,000년 전후의 선사시대 사람들의 생활상을 엿볼 수 있다.','05239 서울 강동구 올림픽로 875 (서울 암사동 유적)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (111,'서울대학교 미술관 MoA','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3319&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','서울대학교 미술관 MoA는 대학교 건물 사이에 자리 잡고 있다. 세계적인 건축가 렘 쿨하스가 설계한 건물로 전시와 교육이 함께 진행된다.','08826 서울 관악구 관악로 1 (신림동, 서울대학교) 서울대학교 미술관 (서울대학교 내)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (112,'떡박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=2039&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','떡박물관은 우리 조상들의 슬기로웠던 삶의 모습과 숨결을 느낄 수 있는 체험공간이다.','03132 서울 종로구 돈화문로 71 (와룡동, 떡박물관)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (113,'사육신공원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=4513&fileTy=POSTTHUMB&fileNo=3&thumbTy=M','사육신공원은 한강대교와 노량진역 언덕에 있는 서울특별시 유형문화재 8번 사육신묘를 가꾸어 만들어졌다.','06902 서울 동작구 노량진로 191 (노량진동, 사육신묘지공원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (114,'광희문','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=23605&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','시구문(屍軀門) ·수구문(水口門)이라고도 하였으며 서소문(西小門)과 함께 시신(屍身)을 내보내던 문이다.','04612 서울 중구 퇴계로 350 (신당동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (115,'아르코 미술관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=18992&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','아르코 미술관은 과거 국립서울대학교 터에 한국문화예술진흥원 산하 미술회관으로 개관되었다.','03087 서울 종로구 동숭길 3 (동숭동, 한국문화예술진흥원)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (116,'윤봉길 의사 기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=3759&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서초구 양재동에 위치한 윤봉길의사 기념관은 지상 2층 규모로 설립되었다.','06773 서울 서초구 매헌로 99',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (236,'DDP 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27229&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','DDP 지하 2층에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04566 서울 중구 을지로 281 (을지로7가, 디자인장터) 지하 2층 종합안내소',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (237,'신촌역사 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27231&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','신촌 구역사에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','03765 서울 서대문구 신촌역로 30 (신촌동, 신촌민자역사) 신촌역사 내',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (238,'DDP 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27229&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','DDP 지하 2층에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04566 서울 중구 을지로 281 (을지로7가, 디자인장터) 지하 2층 종합안내소',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (239,'시민청 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27227&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','시민청 지하 1층에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04524 서울 중구 세종대로 110 (태평로1가, 서울특별시 청사) 지하 1층',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (240,'광화문 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27225&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','광화문에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','03186 서울 종로구 세종대로 149 (광화문빌딩) 동화면세점 앞',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (241,'홍대입구 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27224&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','홍대입구역에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04055 서울 마포구 홍익로 20',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (242,'삼일교 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27221&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종로에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','03190 서울 종로구 청계천로 85 (삼일빌딩) 앞 보도',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (243,'남대문시장 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27219&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','남대문 시장에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04528 서울 중구 남대문시장4길 32 (남대문코코클럽)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (244,'이태원 관광안내소(지하)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27218&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','이태원역사 내에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04350 서울 용산구 이태원로 지하 177 (이태원동, 6호선 이태원역) 이태원역사 내',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (245,'남대문시장 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27219&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','남대문 시장에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04528 서울 중구 남대문시장4길 32 (남대문코코클럽)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (246,'이태원 관광안내소(지하)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27218&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','이태원역사 내에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04350 서울 용산구 이태원로 지하 177 (이태원동, 6호선 이태원역) 이태원역사 내',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (247,'이태원 관광안내소(지상)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27216&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','이태원역 앞에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 예약 서비스, 관광홍보물, 편의시설을 제공한다.','04350 서울 용산구 이태원로 지하 177 (6호선 이태원역) 해밀턴호텔 앞',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (248,'동대문 관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27215&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','동대문역사문화공원역 앞에 위치한 관광안내소로 서울을 방문하는 여행객들에게 여행 정보, 통역 안내 서비스, 관광홍보물, 편의시설을 제공한다.','04564 서울 중구 장충단로 247 (굿모닝시티쇼핑몰)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (249,'용산역관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27195&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','용산역 관광정보센터는 서울 용산역사에 위치해 있는 관광안내소이다.','04377 서울 용산구 한강대로23길 55 (한강로3가, 용산역)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (147,'성신여대 복식박물관 및 자연사박물관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=33828&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','성신여대 제2캠퍼스인 운정그린캠퍼스에는 있는 정원(淨源) 박광훈 복식박물관과 자연사박물관에서 전통 복식과 자연의 역사를 배워 보세요.','01133 서울 강북구 도봉로76가길 55 (미아동, 성신여자대학교운정그린캠퍼스) 운정그린캠퍼스 B1',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (148,'서울하수도과학관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=33825&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','국내외 하수도의 역사?기술?미래상을 전시하고 있는 과학관과 하수처리시설을 직접 견학할 수 있는 물재생센터를 함께 운영하는 현장 중심형 공간입니다.','04809 서울 성동구 자동차시장3길 64 (용답동) 서울하수도과학관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (149,'서울도시재생이야기관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=33824&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','서울도시재생이야기관은 도시재생에 대한 정보와 비전을 나누고 도시재생을 함께 만드는 사람들의 발자취를 공유하는 공간입니다.','03178 서울 종로구 송월길 2 (신문로2가, 서울도시건축센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (267,'통문관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=25930&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','통문관은 1934년부터 이어져 왔다. 우리 귀에 익은 국보급, 보물급 문화재들이 통문관을 거쳐 세상의 빛을 보게 됐다.','03145 서울 종로구 인사동길 55-1 (관훈동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (268,'납청놋전','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=25928&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','납청놋전은 납청 지역에서 만들던 그 방식을 그대로 이어오고 있는 놋그릇 집이다.','03146 서울 종로구 인사동10길 5 (관훈동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (269,'갤러리 3안','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=25060&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','삼청동에 개관한 갤러리 3안은 회화, 영상, 조각, 설치 외 다양한 예술 분야를 다루고 있으며 구애받지 않는 실험 정신을 가진 아티스트들의 작품을 감상할 수 있다.','03053 서울 종로구 북촌로 137-7 (삼청동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (270,'인천공항 제2여객터미널 관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24807&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인천공항 제2여객터미널에 위치한 관광정보센터로 2018년 1월 18일에 개관하였다.','22382 인천 중구 공항로 272 (운서동, 인천공항) 제2여객터미널 입국장',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (271,'SJ쿤스트할레','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24732&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','SJ쿤스트할레는 회의과 토론을 하는 문화예술적 플랫폼으로 만들어져 전시, 파티, 공연, 패션쇼, 워크숍 같은 프로그램과 연계된 일상 예술을 제공한다.','06054 서울 강남구 언주로148길 5 (논현동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (272,'종로양복점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24708&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','종로 양복점은 1916년부터 이어져 왔다. 자그만치 100년이라는 시간이 흘렀다. 가게로 들어가면 오래된 다리미와 재단용 가위가 진열되어 있어 박물관을 연상케한다.','04551 서울 중구 수표로 45 (저동2가, 비즈센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (273,'국선옻칠','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24705&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','국선옻칠은 1977년부터 이어온 나전칠기 공예품을 파는 오래된 가게이다. 40년의 역사를 가진 공예점이며, 2대에 걸쳐 가게를 운영하고 있다.','03195 서울 종로구 창경궁로 88 (예지동) 광장3층 2390호',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (274,'구하산방','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24703&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','인사동 구하산방은 1915년 문을 열었다. 고종 황제와 순종 황제가 찾았던 붓집으로 100년이 지난 지금까지 문방사우를 팔고 있다.','03162 서울 종로구 인사동5길 11 (인사동)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (275,'동대문디자인플라자 (DDP)','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24679&fileTy=POSTTHUMB&fileNo=2&thumbTy=M','2006년 서울특별시청이 계획한 동대문디자인플라자(DDP)는 2014년 3월 21일 문을 열었다.','04566 서울 중구 을지로 281 (을지로7가, 디자인장터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (276,'코엑스','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=24663&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','이 컨벤션센터는 국제회의와 국제적 리셉션, 업무 세미나와 소규모 회의 같은 대형 이벤트를 제공하는 콘퍼런스홀이 특징이다.','06164 서울 강남구 영동대로 513 (삼성동, 코엑스)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (254,'영등포관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27191&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','영등포관광정보센터는 서울 서남권 중심거점이자 하루 수십만의 유동인구가 지나고 있는 타임스퀘어 광장에 2017년 9월 개관했다.','07305 서울 영등포구 영중로 15 (영등포동4가, 타임스퀘어)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (255,'마포관광정보센터','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27190&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','마포관광정보센터는 홍대입구역 7번 출구에서 도보 3분 거리에 있는 관광안내소이다.','04051 서울 마포구 어울마당로 145-3 (서교동, 마포관광정보센터)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (256,'북촌마을관광안내소','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27189&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','북촌마을안내소는 정독도서관 내 부지를 활용하여 2014년 8월 건립되었으며 영어, 일본어, 중국어가 가능한 관광안내사를 통해 관광객을 위한 관광정보 제공 및 통역 안내서비스를 제공한다.','03055 서울 종로구 북촌로5길 48 (화동, 정독도서관) 정독도서관 부지내, 서울교육박물관 앞',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (257,'초대길','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27112&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','초대길은 강북구 근현대사기념관 개관을 기념하여 새롭게 기획된 둘레길 코스이다.','01013 서울 강북구 4.19로 114 (수유동) 근현대사기념관 (출발)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (258,'근현대사기념관','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=27105&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','근현대사기념관은 독립정신과 민주주의의 뜻을 제대로 기억하고 전파하기 위해 설립되었다.','01013 서울 강북구 4.19로 114 (수유동) 근현대사기념관',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (259,'한영양복점','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26956&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','올해로 85년의 역사를 맞이한 한영양복점은 맞춤 양복점 중에서도 품질이 좋기로 유명한 곳이다.','04631 서울 중구 퇴계로20길 2 (남산동2가, 퍼시픽호텔)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (260,'박인당','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26954&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','박인당은 대한민국 정부가 인정한 명장이 도장을 파주는 곳이다.','03189 서울 종로구 청계천로 55 (관철동, 대신빌딩) 302호',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (261,'문화이용원','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26953&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','문화이용원은 올해로 78년 된 이발소다.','03075 서울 종로구 혜화로 7 (명륜2가)',0);
Insert into HR.SEOUL_LOCATION (NO,TITLE,POSTER,MSG,ADDRESS,HIT) values (262,'공근혜갤러리','https://korean.visitseoul.net/comm/getImage?srvcId=POST&parentSn=26676&fileTy=POSTTHUMB&fileNo=1&thumbTy=M','공근혜갤러리는 2005년 개관 이래로 해외 유명 사진작가들을 국내에 처음 소개하며 한국 사진계에 큰 영향력을 끼친 화랑으로 이름을 알려왔다.','03049 서울 종로구 삼청로7길 38 (삼청동)',0);
--------------------------------------------------------
--  DDL for Index SL_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SL_NO_PK" ON "HR"."SEOUL_LOCATION" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEOUL_LOCATION
--------------------------------------------------------

  ALTER TABLE "HR"."SEOUL_LOCATION" MODIFY ("TITLE" CONSTRAINT "SL_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_LOCATION" MODIFY ("POSTER" CONSTRAINT "SL_POSTER_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_LOCATION" MODIFY ("MSG" CONSTRAINT "SL_MSG_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_LOCATION" MODIFY ("ADDRESS" CONSTRAINT "SL_ADRESS_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEOUL_LOCATION" ADD CONSTRAINT "SL_NO_PK" PRIMARY KEY ("NO")
  USING INDEX "HR"."SL_NO_PK"  ENABLE;
