CREATE TABLE salary (
    sno   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id NUMBER NOT NULL,
    pay_date    DATE NOT NULL,          -- 급여 지급일
    amount      NUMBER(10,2) NOT NULL  -- 지급 금액
 );
CREATE TABLE attendance (
    ano   NUMBER PRIMARY KEY,  -- 출퇴근 기록 ID
    id     NUMBER NOT NULL,                    -- 사원 ID
    work_date        DATE NOT NULL,                   -- 근무일
    check_in_time   VARCHAR2(20),                        -- 출근 시간
    check_out_time  VARCHAR2(20)                        -- 퇴근 시간
   );

CREATE TABLE loan (
    lno        INT AUTO_INCREMENT PRIMARY KEY,  -- 대출 ID
    id        INT NOT NULL,                    -- 회원 ID
    bookno        INT NOT NULL,                    -- 도서 ID
    loan_date      DATE NOT NULL,                   -- 대출일
    due_date       DATE NOT NULL,                   -- 반납 예정일
    return_date    DATE,                            -- 실제 반납일
    status         VARCHAR(20) DEFAULT 'BORROWED',  -- 상태 (BORROWED, RETURNED, OVERDUE)
 );
 
 CREATE TABLE books
(
   no NUMBER,
   bookname VARCHAR(2000) CONSTRAINT books_bn_nn NOT NULL,
   poster VARCHAR2(260) CONSTRAINT poster_bn_nn NOT NULL,
   author VARCHAR2(1000) CONSTRAINT author_bn_nn NOT NULL,
   price VARCHAR2(100) CONSTRAINT price_bn_nn NOT NULL,
   pubdate VARCHAR2(100) CONSTRAINT pub_bn_nn NOT NULL,
   isbn VARCHAR2(100) CONSTRAINT isbn_bn_nn NOT NULL,
   content CLOB,
   tag CLOB,
   CONSTRAINT books_no_pk PRIMARY KEY(no)
);
 desc books;

-- 시퀀스
CREATE SEQUENCE books_no_seq
     START WITH 1
     INCREMENT BY 1
     NOCYCLE
     NOCACHE

-- 인덱스 잡기
CREATE INDEX idx_books_bn ON books(bookname);
CREATE INDEX idx_books_bn ON books(tag); // 검색이 많은 컬럼에 대해 인덱스를 만들어 준다, pk,uk는 자동으로 인덱시 만들어짐

SELECT count(*) FROM books;
SELECT * FROM books;


CREATE TABLE member(
    id VARCHAR2(20),
    pwd VARCHAR2(10) CONSTRAINT mem_pwd_nn NOT NULL,
    name VARCHAR2(51) CONSTRAINT mem_name_nn NOT NULL,
    sex VARCHAR2(6),
    post VARCHAR2(7) CONSTRAINT mem_post_nn NOT NULL,
    addr1 VARCHAR2(200) CONSTRAINT mem_addr1_nn NOT NULL,
    addr2 VARCHAR2(200),
    phone VARCHAR2(14),
    content CLOB,
    isAdmin CHAR(1) DEFAULT 'n',
    regdate DATE DEFAULT SYSDATE,
    CONSTRAINT mem_id_pk PRIMARY KEY(id),
    CONSTRAINT mem_sex_ck CHECK(sex IN('남자','여자')),
    CONSTRAINT mem_phone_uk UNIQUE(phone)
);



        
CREATE TABLE buy(
   no NUMBER,
   id VARCHAR2(20),
   type NUMBER CONSTRAINT buy_type_nn NOT NULL,
   gno NUMBER CONSTRAINT buy_gno_nn NOT NULL,
   account NUMBER DEFAULT 0,
   price NUMBER DEFAULT 0,
   regdate DATE DEFAULT SYSDATE,
   CONSTRAINT buy_no_pk PRIMARY KEY(no),
   CONSTRAINT buy_id_fk FOREIGN KEY(id)
   REFERENCES member(id)
);

create sequence buy_no_seq
        start with 1
        increment by 1
        nocycle
        nocache;
        
desc buy;

SELECT * FROM buy;
-- join
select b.no,goods_poster,goods_name,account,regdate,price
from buy b join goods_all g
on b.gno = g.no
order by regdate desc;


INSERT ALL
INTO member VALUES ('user01','pw01','김민수','남자','06234','서울특별시 강남구 역삼동','','010-1111-0001','안녕하세요','n',SYSDATE)
INTO member VALUES ('user02','pw02','이서연','여자','05510','서울특별시 송파구 잠실동','','010-1111-0002','반갑습니다','n',SYSDATE)
INTO member VALUES ('user03','pw03','박지훈','남자','48058','부산광역시 해운대구 우동','','010-1111-0003','잘 부탁드립니다','n',SYSDATE)
INTO member VALUES ('user04','pw04','최수진','여자','42012','대구광역시 수성구 범어동','','010-1111-0004','가입했습니다','n',SYSDATE)
INTO member VALUES ('user05','pw05','정우성','남자','21984','인천광역시 연수구 송도동','','010-1111-0005','안녕하세요','n',SYSDATE)
INTO member VALUES ('user06','pw06','한지민','여자','61186','광주광역시 북구 용봉동','','010-1111-0006','좋은 하루','n',SYSDATE)
INTO member VALUES ('user07','pw07','윤아름','여자','34187','대전광역시 유성구 봉명동','','010-1111-0007','반가워요','n',SYSDATE)
INTO member VALUES ('user08','pw08','강동원','남자','44705','울산광역시 남구 삼산동','','010-1111-0008','잘 부탁해요','n',SYSDATE)
INTO member VALUES ('user09','pw09','조현우','남자','13590','경기도 성남시 분당구','','010-1111-0009','가입완료','n',SYSDATE)
INTO member VALUES ('user10','pw10','임수정','여자','16514','경기도 수원시 영통구','','010-1111-0010','안녕하세요','n',SYSDATE)

INTO member VALUES ('user11','pw11','오지훈','남자','24339','강원도 춘천시','','010-1111-0011','반갑습니다','n',SYSDATE)
INTO member VALUES ('user12','pw12','배수지','여자','28624','충청북도 청주시','','010-1111-0012','잘 부탁드립니다','n',SYSDATE)
INTO member VALUES ('user13','pw13','서강준','남자','31162','충청남도 천안시','','010-1111-0013','안녕하세요','n',SYSDATE)
INTO member VALUES ('user14','pw14','김하늘','여자','54999','전라북도 전주시','','010-1111-0014','가입했어요','n',SYSDATE)
INTO member VALUES ('user15','pw15','이종석','남자','58613','전라남도 목포시','','010-1111-0015','반갑습니다','n',SYSDATE)
INTO member VALUES ('user16','pw16','박보영','여자','37759','경상북도 포항시','','010-1111-0016','안녕하세요','n',SYSDATE)
INTO member VALUES ('user17','pw17','정해인','남자','51430','경상남도 창원시','','010-1111-0017','잘 부탁해요','n',SYSDATE)
INTO member VALUES ('user18','pw18','김지원','여자','63243','제주특별자치도 제주시','','010-1111-0018','가입 완료','n',SYSDATE)
INTO member VALUES ('user19','pw19','송중기','남자','04038','서울특별시 마포구','','010-1111-0019','안녕하세요','n',SYSDATE)
INTO member VALUES ('user20','pw20','전지현','여자','04389','서울특별시 용산구','','010-1111-0020','반갑습니다','n',SYSDATE)

INTO member VALUES ('user21','pw21','김수현','남자','03027','서울특별시 종로구','','010-1111-0021','안녕하세요','n',SYSDATE)
INTO member VALUES ('user22','pw22','아이유','여자','05247','서울특별시 강동구','','010-1111-0022','잘 부탁드려요','n',SYSDATE)
INTO member VALUES ('user23','pw23','차은우','남자','10450','경기도 고양시','','010-1111-0023','가입했습니다','n',SYSDATE)
INTO member VALUES ('user24','pw24','김세정','여자','17019','경기도 용인시','','010-1111-0024','안녕하세요','n',SYSDATE)
INTO member VALUES ('user25','pw25','이승기','남자','01689','서울특별시 노원구','','010-1111-0025','반갑습니다','n',SYSDATE)
INTO member VALUES ('user26','pw26','손예진','여자','06611','서울특별시 서초구','','010-1111-0026','잘 부탁해요','n',SYSDATE)
INTO member VALUES ('user27','pw27','현빈','남자','01074','서울특별시 강북구','','010-1111-0027','가입완료','n',SYSDATE)
INTO member VALUES ('user28','pw28','김태리','여자','04790','서울특별시 성동구','','010-1111-0028','안녕하세요','n',SYSDATE)
INTO member VALUES ('user29','pw29','박서준','남자','08789','서울특별시 관악구','','010-1111-0029','반갑습니다','n',SYSDATE)
INTO member VALUES ('user30','pw30','한소희','여자','07025','서울특별시 동작구','','010-1111-0030','잘 부탁드립니다','n',SYSDATE)

INTO member VALUES ('user31','pw31','유아인','남자','02123','서울특별시 중랑구','','010-1111-0031','안녕하세요','n',SYSDATE)
INTO member VALUES ('user32','pw32','김고은','여자','05072','서울특별시 광진구','','010-1111-0032','가입했습니다','n',SYSDATE)
INTO member VALUES ('user33','pw33','이도현','남자','03312','서울특별시 은평구','','010-1111-0033','반갑습니다','n',SYSDATE)
INTO member VALUES ('user34','pw34','장원영','여자','05552','서울특별시 송파구','','010-1111-0034','안녕하세요','n',SYSDATE)
INTO member VALUES ('user35','pw35','안효섭','남자','07505','서울특별시 강서구','','010-1111-0035','잘 부탁해요','n',SYSDATE)
INTO member VALUES ('user36','pw36','수지','여자','08511','서울특별시 금천구','','010-1111-0036','가입완료','n',SYSDATE)
INTO member VALUES ('user37','pw37','로운','남자','08378','서울특별시 구로구','','010-1111-0037','안녕하세요','n',SYSDATE)
INTO member VALUES ('user38','pw38','김유정','여자','01369','서울특별시 도봉구','','010-1111-0038','반갑습니다','n',SYSDATE)
INTO member VALUES ('user39','pw39','지창욱','남자','03737','서울특별시 서대문구','','010-1111-0039','잘 부탁드립니다','n',SYSDATE)
INTO member VALUES ('user40','pw40','박신혜','여자','08015','서울특별시 양천구','','010-1111-0040','안녕하세요','n',SYSDATE)

INTO member VALUES ('user41','pw41','이민호','남자','07328','서울특별시 영등포구','','010-1111-0041','반갑습니다','n',SYSDATE)
INTO member VALUES ('user42','pw42','김소현','여자','04390','서울특별시 용산구','','010-1111-0042','잘 부탁해요','n',SYSDATE)
INTO member VALUES ('user43','pw43','남주혁','남자','03045','서울특별시 종로구','','010-1111-0043','가입했습니다','n',SYSDATE)
INTO member VALUES ('user44','pw44','문가영','여자','04524','서울특별시 중구','','010-1111-0044','안녕하세요','n',SYSDATE)
INTO member VALUES ('user45','pw45','김선호','남자','06236','서울특별시 강남구','','010-1111-0045','반갑습니다','n',SYSDATE)
INTO member VALUES ('user46','pw46','이성경','여자','02845','서울특별시 성북구','','010-1111-0046','잘 부탁드립니다','n',SYSDATE)
INTO member VALUES ('user47','pw47','박형식','남자','05278','서울특별시 강동구','','010-1111-0047','안녕하세요','n',SYSDATE)
INTO member VALUES ('user48','pw48','조이','여자','04039','서울특별시 마포구','','010-1111-0048','가입완료','n',SYSDATE)
INTO member VALUES ('user49','pw49','도경수','남자','02565','서울특별시 동대문구','','010-1111-0049','반갑습니다','n',SYSDATE)
INTO member VALUES ('user50','pw50','김다미','여자','02124','서울특별시 중랑구','','010-1111-0050','안녕하세요','n',SYSDATE)
SELECT * FROM dual;
commit;



